apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- storage.yaml
- relay-secrets.sops.yaml
- relay-migrations.sops.yaml
- relay-postgres.sops.yaml
- relay-backup.sops.yaml
- postgres.yaml
- relay.yaml
- network-policy.yaml
- postgres-bootstrap.yaml
- backup.yaml
