apiVersion: v1
kind: Secret
metadata:
    name: relay-secrets
    namespace: relay
    labels:
        app.kubernetes.io/part-of: relay
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:86+7f7vgdwoetfiWDt+pyC3GrXMJ0F9GQ2QogcXBrz7A3ZzriU76Cf0BXJtfoRMJk2z3zP1IoI8HRpsziMmcAeKdqh41Dpc9vSiE9u/sbsezvqtgRYAXPSQ0N6pE50vXw9UAgfJ0jeeTpr8Djr/8oAYa11M=,iv:wXF8wGeIhaS0LBcheut2dilHcCHluwoAT71luPYJ+lQ=,tag:7aKaYgNESkqjK8svdK0pag==,type:str]
    APP_DATABASE_URL: ENC[AES256_GCM,data:Zn/avubDnQuv1VvAx1HumrgOzZawqZOzTcI/kBEco3VCnw1ql4kPzMp/0ydnjXChPnDmisuYgv8SC1G7Kb/LRC35w4JUzbU6tlvJ2GIb4V/EKEEAn82Ac+2+OKFtUGsTNxbz74oMFyRht4tMZtXij296,iv:p9X1U8Kcp9ui2bPFpmkxxvRn4DlBtrNrhJJmyMeWzCs=,tag:zidB/Bke2Snc5tn/pgWGNg==,type:str]
    RELAY_ADMIN_TOKEN: ENC[AES256_GCM,data:OowHYCbFfafp9e1zWn1Vz2VyFCZPok539JPGF17HyXfEbLH433alidVMlr+koh4T,iv:MyQkJjjQgOjuvqzKffwdTLrdcJj3NN1pO2KyL7GeyjA=,tag:mmhUJs+Pj5fljcPO5yC8fg==,type:str]
    RELAY_LLM_KEY: ENC[AES256_GCM,data:/b5etP0Dz9dLhUoWTJnYsG/mGGf84Wt8LQKcALpqclEhEmZrVXsvaBbTTRgBciE=,iv:YBbLBvsmxMsRJc1CYlYWVXDUZj7v7zXDSvZxUXPhz7U=,tag:9y0MI3NuA/8lCnhZZSqHSw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYnUyU25vQkh4ZlBtQWVs
            djR4cFVCeHNMdHpHaHI1MVZwSGR6VFFNOEUwCjNzS1NNNDkvV0Q0OTNITWo3cWFI
            TW1Bd1FaNGIwNVEyZzFGMWZrUWQzNDgKLS0tIHg4UG9LbzNXbFJlRUVVR09UKzZz
            MnZvdG1Ra0Nib0w4SkxLYzkvMlVqM0kKi1AqTpQ+VEn/iTpqfJE+UruS+fiVDX0e
            RvG5w3tup0ClPECO7TGYkvVdKvjQqokC4GHDBeTBFRFIhI2PmZFgYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g0exjqgq9l52m8g7hqkqelc3kcam4wwlkngzjhn5wv6dzxfjdceqdyfl4t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T21:33:23Z"
    mac: ENC[AES256_GCM,data:ai43ODITul/eoMzEIWsewYowQ/mu82M+fuwSIEhN4lqRgydzIZ2zR3f3xYgE+gC8+lobBUYGKkP0MBHk2ZLA1O733JOotsGmN/FZn+TNMKxAEv817lKcHVGso8wT3IipiAJAn+T01ODLqQN3LEx/L3EBvz895CK92I8M3OtaVog=,iv:lXK79v0PwIw9BDffWWfUTYAtlWapYpnH4puE3ODim3s=,tag:OHXAK/eRcReiXA+hzHRHyg==,type:str]
    version: 3.12.2
