apiVersion: v1
kind: Secret
metadata:
    name: relay-backup
    namespace: relay
    labels:
        app.kubernetes.io/part-of: relay
type: Opaque
stringData:
    PGPASSWORD: ENC[AES256_GCM,data:UZ3TD18LmZSMENoTMpjYtRNBcib31hVscfHCq4vQZRS7gF9TR9yPF9NOUXBtpWcI,iv:/vmVoogQfPkRnJ2WbK10Tt5vLxSr0Y+Nv4Dc38uvI08=,tag:Pah9/7vqwTgSpyVJOwDSfw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dkNJRnV4NVduY2w5WU1p
            YmtVL0dpemtvcHlWYTFNbGZOanB1c3B2cFNZCkVPSXlKNW9CYkEyWjZhQTZBZWZ1
            b2Z0YUlxWnVFazFKWWJvMk8rOERNT0EKLS0tIHg5QVJ1VkNGR3FZZmlrMFVCN3hV
            a05Wa254dXdaSDFHaGlBRUVtR1lWRVEKJg77SKUQipKa9LHkT12QnNmQG32/or41
            hfagKS0Ieg56L2tK+1rw1iVhQwEAJkPDorADTIHXfFEIzV9FAlBl1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g0exjqgq9l52m8g7hqkqelc3kcam4wwlkngzjhn5wv6dzxfjdceqdyfl4t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T21:33:23Z"
    mac: ENC[AES256_GCM,data:LJD4dCyNWG3PHb7rQ0Ut+MLJ0xyVvRr7fDaplP2nV8yungRP6yS9qIhSDaTp965aDXyD4riAExJIW8q7XJ2m3OkuCoPT45p/iHGFWBAY5VrruJZWrpRDmLvqrjpEOgkTnjm/kF0kcP3h6MAPbudy2SEec4qck3EeJP40dgi7zrI=,iv:Ao/725Ji1bjk70gVJgrDr31+Z7excqkD/ldT5gQ3CJ0=,tag:GoANWXUu+neevI3n1Hf2hQ==,type:str]
    version: 3.12.2
