apiVersion: v1
kind: Secret
metadata:
    name: relay-secrets
    namespace: relay
    labels:
        app.kubernetes.io/part-of: relay
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:eaUssXaDH63GFY+UcPeifCuQTeVtRxB6nmwtCugOAIITbSaEgaHtgacgBuQBtGlK01Cv3aYOI23QVcsAKIfVOm9DliM89foGh8OYd4ytswbgyWSSVdNWR38bdvuzdhF9QmUl2gUKyPiCVgm7D7gqjZZbfEY=,iv:wXF8wGeIhaS0LBcheut2dilHcCHluwoAT71luPYJ+lQ=,tag:/1/HIXQkePDTjXNCBQIYxg==,type:str]
    APP_DATABASE_URL: ENC[AES256_GCM,data:VtuLvMZLPPZQwV5ssqPtueJbEReqDrTd0hFDk+MO3mHzNJfS2/4KwK0oJrQp4CJGL60DCiIofoWr7LFIeqk1q2oggCUmnW79jOiVrPLRAuWboKQzZ6xaf9qNFutnZorv3w/LrF1nnOsI3BdNl6iwCtC2,iv:p9X1U8Kcp9ui2bPFpmkxxvRn4DlBtrNrhJJmyMeWzCs=,tag:WkKVStyA3ETyFu0/4g4PZQ==,type:str]
    RELAY_ADMIN_TOKEN: ENC[AES256_GCM,data:+5AdcaEBFeZq4y3G2gPiLPSEacBbZ8Uh7+9qp2AzTmiWs/XCmFqqE0lLF2WALnEB,iv:MyQkJjjQgOjuvqzKffwdTLrdcJj3NN1pO2KyL7GeyjA=,tag:Dg2SlRUEJoNiEKUjQ3THSg==,type:str]
    RELAY_LLM_KEY: ENC[AES256_GCM,data:y3lJj8CHuNipFMeXh+ZxeHc+/vgWYwljUO+lnmTVU9ih5aqn/hwABhqSGQmgacI=,iv:YBbLBvsmxMsRJc1CYlYWVXDUZj7v7zXDSvZxUXPhz7U=,tag:nW0+EBLOQ7X7VoibDEW83Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQ3RobVBjOEpTTWFRMTlX
            Ny9XK1QvbXUzL0xlM1R2SmIrTVhVM256SFRjCkk4bmtqQUF0dVA1dk5JUW5mR1Z1
            RHVKMWMzUkxEd1lrTWtuVEh5ZDZoQVUKLS0tIHNqbFZWYS9EMlBGbTBlOVVLNnAx
            WVhhZldiekpXbzhEU3BGOE9peUd3ZEEKAQuY4CMrs9lnnS0UOl/XSZT56S1HYnFc
            iiUxffywJWkKnCOQR10cKTiyvRJWXF+g0QiOR6Yis7zTFtsFygRfhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfa6hhdz9egnje3nwa2k0gpk5nr29nyvu74eprk20m7ql4fhw4esrlmt5g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcTVGQklvamt4VGJ3MXZ4
            eWw4SlUxUGZxMG1yUGhmY2hKVE5TNjlxRVYwCjJ3NkNxU2ZseXhjNDU3RGxWNytJ
            Rlo0VThQN0VBbENYWDh6TlNoOC9HM3MKLS0tIHA0REl5VlR5aDJBTkoxTXNTRXJ3
            T0dQbHBxL3FQdUN6S3M2TTIvck1UZFkKzr9K8utQzEokOmXVgNTkWPiso7U4jvS3
            KJR9j1bcSLp+3Cw3St8qhAauUqUcdJNMfm7prUN0rQMdQtECIMsUCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g0exjqgq9l52m8g7hqkqelc3kcam4wwlkngzjhn5wv6dzxfjdceqdyfl4t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T18:47:42Z"
    mac: ENC[AES256_GCM,data:+n662RVk3JXapQwIGu5QrqFZypxJ/RkAsL0i2MfeHmnCb1k52PLRbtIhGcVWFS4OB3+38CmKtKB+nOKPUCl5hHvigxs3o4emCbYGJHAJ3UpqoEmdho0Aqq/Rb9utpSHmvFOxW/trdEeZq/xuIxN7Wd17cnviD3cS8KPeCYFygX0=,iv:IcCHrYjXncAYx6K2G8F7dbnH8/EYbXzB/8xWKFkggeU=,tag:bqO0yjo0nxnjhqzuNYOqFA==,type:str]
    version: 3.12.2
