apiVersion: v1
kind: Secret
metadata:
    name: relay-secrets
    namespace: relay
    labels:
        app.kubernetes.io/part-of: relay
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:B6ynUw5AbdKBs9SYem1HQ13wz7uaNFZikkLGYhPOGpYvuDxIyyKW61cyEtTCcyoCoxCjq66/EBL7tSaA9DkZSuOyu4H3oKrUIhDLb8SrIgIko4ERr6xOxSzAw/a3k8+7w/ZXo7JqImmIlj0bKlyflG4YYbI=,iv:JB8Rf0H7n89qb6JO9h/+plvfjKwDnHnyNf4GQeNie8E=,tag:Kn2MRBCFJVbjAU6OYP2L7g==,type:str]
    APP_DATABASE_URL: ENC[AES256_GCM,data:fbrN2S4+UHViSplDX1B9EOYdxR8cZsDJoKlZzOGHEzL7VRRt9iNJZt2qC5v3ofVSQyO8DqGWp2sSTBk5QqVwQXzZj6sMJh6Gxxtj4i3fXpX/tkucwuBd/UK1i0Jt4ONmELn0Tv1m/CRHVcRFjdgFU7dh,iv:nzOp4xcmPWwhVIzG9rVjRs2PdoRuOoxlYsp5r59ZT/o=,tag:fJU9k0NGnaDjHgm7+gb1eA==,type:str]
    RELAY_APP_DB_PASS: ENC[AES256_GCM,data:2KGYDuB9xj9atIRFUWYwoFUcoatZEFW/DJP47XTBh4axQGuUPaAVyklhkw==,iv:lO/vhvq/EqLy/l9U5MVr51F8ClQ5wYKEaxnDgs2vBwE=,tag:zfcnteewpsIvrZPY5LT0tQ==,type:str]
    RELAY_ADMIN_TOKEN: ENC[AES256_GCM,data:CVYweMd9A7XKssVv6tLncjRA6ixGA3piS5TZdLzYZMtpyR4KDzXX0iC3ZHAWyxfV,iv:kReJOAcAgJcTFZH43u2ZnKQSStncv31NO0FMETuqs3I=,tag:dsktJylBb3ebjrybBvNXMQ==,type:str]
    RELAY_LLM_KEY: ENC[AES256_GCM,data:hvfoiMOZTRoun6WUDSDi5+sBy/xfb6hZWxXQDaGwALKKIARTahSWWY5bqBP0uk4=,iv:ahQp6dbPrr7lXnnFuKjsVeSvg8OZOgZJ8R23JoUuSxA=,tag:kt8cGbg3izFSll8nfZST7w==,type:str]
sops:
    age:
        - recipient: age1nfa6hhdz9egnje3nwa2k0gpk5nr29nyvu74eprk20m7ql4fhw4esrlmt5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWkU4b1lsaXlEbklyOUhn
            aFcwRTBmZnFUL3h4YlB6WkV4ODBHQzQxUENRCk5wZEpQeFFhVm9rMXczUnVQMDhI
            SkhHbUNaTnhLdWV2R1FHSlo3dHZWdWMKLS0tIC8zTzJiZVhIS2laSW5oVlYrWnRj
            UXRjYVN5S3lFOHVWRHBUZFpTWTdpcmsKdUXDC/fZjzckhTsuVLK9Wope72fsHUmL
            TU3p/5X1U8dx9PjMEVHz0E4PFnS6+lm0ITib15wgfjHvNX80a2tZrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-01T17:59:38Z"
    mac: ENC[AES256_GCM,data:VBQtiqeXCNBJwFmqf1hJ9nI1zenTW9Jbj5MyrB/Fev2AbY5l2o9vdGDEN7P4vJqyd6PrdyFGadwVNcX9TYUZMyzhv3qr9tRIenhQUco4HWgTA+KW84E41Mse1TCw/xZeE4po9UVyO9LpvOAo5OGm7Dj8evpZQOK/8hG5/gs++9I=,iv:wPkP+ZXtRlRomIBPpyHXRWnDo/lvuN2ojk2NLoTpyHY=,tag:Qi88WbW8owi5yjvmJGG02g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: relay-postgres
    namespace: relay
    labels:
        app.kubernetes.io/part-of: relay
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:Wi0o1/f5qxIWmSjaLO6Gb5kp6nhx+s7MCGHudpl9ah2TzK4QVaPI3nNosQ==,iv:uf4bjp1D97oGy0tvTVcG721q+OPqq70gr9AonE+Krog=,tag:ESie4NLMWVXx+1sqNdJ+rA==,type:str]
sops:
    age:
        - recipient: age1nfa6hhdz9egnje3nwa2k0gpk5nr29nyvu74eprk20m7ql4fhw4esrlmt5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWkU4b1lsaXlEbklyOUhn
            aFcwRTBmZnFUL3h4YlB6WkV4ODBHQzQxUENRCk5wZEpQeFFhVm9rMXczUnVQMDhI
            SkhHbUNaTnhLdWV2R1FHSlo3dHZWdWMKLS0tIC8zTzJiZVhIS2laSW5oVlYrWnRj
            UXRjYVN5S3lFOHVWRHBUZFpTWTdpcmsKdUXDC/fZjzckhTsuVLK9Wope72fsHUmL
            TU3p/5X1U8dx9PjMEVHz0E4PFnS6+lm0ITib15wgfjHvNX80a2tZrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-01T17:59:38Z"
    mac: ENC[AES256_GCM,data:VBQtiqeXCNBJwFmqf1hJ9nI1zenTW9Jbj5MyrB/Fev2AbY5l2o9vdGDEN7P4vJqyd6PrdyFGadwVNcX9TYUZMyzhv3qr9tRIenhQUco4HWgTA+KW84E41Mse1TCw/xZeE4po9UVyO9LpvOAo5OGm7Dj8evpZQOK/8hG5/gs++9I=,iv:wPkP+ZXtRlRomIBPpyHXRWnDo/lvuN2ojk2NLoTpyHY=,tag:Qi88WbW8owi5yjvmJGG02g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
