apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: relay-releases
  namespace: relay
  labels:
    app.kubernetes.io/part-of: relay
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: relay-data
  namespace: relay
  labels:
    app.kubernetes.io/part-of: relay
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: qnap-iscsi
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: relay-postgres-data
  namespace: relay
  labels:
    app.kubernetes.io/part-of: relay
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: qnap-iscsi
  resources:
    requests:
      storage: 5Gi
