# versitygw access key scoped to the `talos-etcd-backups` bucket (owner).
apiVersion: v1
kind: Secret
metadata:
    name: talos-backup-garage
    namespace: talos-backup
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:w6N55vWbu2meSVlsi87sI6mjpRs=,iv:NK8dmupIdyx6iXaGwXQ+2TX0BDCl7f3SinW5+v61Js8=,tag:wz8LteohE1zo/jwsuGCOew==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:OBZ7wbkREtfDq5jqPnOVc4+0vrelp3BswK7jt5Eq1wp1uE19oFS5qA==,iv:7BLftWGHpUHl/7qZ8NIBcYrZ4I5FjIBQN1HJqpN1aqY=,tag:xSz6860X6ks6jbw35vLUEg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bkxyREllUVVtb250bWJk
            VGU0S1RMK21QQy9jQTlmNkZ0ekt0QnNnMlRBCkJyUWJUbitiZWZ2eHRWZmg5ZnVn
            NnY3MmdrSkZTR1hYWGc1QktwdG1JT0UKLS0tIFZUSVZTZmgwT0U5SHVVaGkvVE5D
            T0ZRWEcwemNaVi9EVENnS21FNms4STgKU6odOfKEF9pRZf8iMSN+01DHm+wh/ryg
            Efl/g8/CV6fvAhk5w4EZfpE83zk6K/tI7rVglN0fY8nGVCg5s2ilPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfa6hhdz9egnje3nwa2k0gpk5nr29nyvu74eprk20m7ql4fhw4esrlmt5g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdGE5U0hMU3FpRHp5amM2
            ZlhWRHZvYTdUb2k3R1Y0WnExSkhCMXJ6aDJBCjRJZEJHenB6QmVXQzZwdzNhUTBw
            d0IzMXNlR2QzZVh5SVhpZXpUKzk5eHMKLS0tIDJKSy8vU3NyS0dnSjVCNU5HS1Bi
            UWJIeEo4Wkp6Y2NVSmZFYzV5TFlidzQKPWi3gbMADp9Rok1GJi4UrM9Wa++xr1+m
            xZ9qci1kHNASxoNyNraP2055M+rzLnqIQ2wIfIrUWxhoG8Q/SO8Erw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g0exjqgq9l52m8g7hqkqelc3kcam4wwlkngzjhn5wv6dzxfjdceqdyfl4t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T13:04:23Z"
    mac: ENC[AES256_GCM,data:wKPOTamD/firwqcGY2wE5w67YO19h6VLlikOKP/SY8BY0ytnuNKT1YyxRlmMiDMiG7yL5pwKWiVKTSHyqM4Z+c5vZaRl0/vdqijn8Obc4oQxwU4ER9KH5+xvSwwF9OXGjv+Sva5FsfdqapoI3sebwE+DROE2CIQ3JEJ8oCdaDuA=,iv:X3J3IxO+ZW0ru19fUmBszWiedgMHlQHMMiIzDHsK1uk=,tag:ydY3w2MxauVJ7/D72j17JQ==,type:str]
    version: 3.13.1
