registry_ci_password: ENC[AES256_GCM,data:095PXieMfcSvNAkZ9/uV89GrwSPkTSeoTpufleCdhTc=,iv:VQ3YabT7YJ5ubo+apREKjJih7rhyf9qPrVlrcZTDlZg=,tag:K878dhif89wN8atz5HW/zA==,type:str]
cloudflare_dns_api_token: ENC[AES256_GCM,data:EBbgRtqTl/SMsLqXQkcphBAad7zUARc4K5YvJjgMrxGqZ0QEqoi8CuJLFH9aJ4sW/YHab6c=,iv:HzTO6B1l1n1A0KiDQ/iA8CCNLGONAbAoNx0JybAh6Yw=,tag:hnNxM2IlPkCKQzdbO7NlOg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcldVQkFtQS9WeEFKN2RL
            cVRBZWJJUzN4WTFQeHNDTmlnVDlHYVUyS0RJCkxqd2tlcG9IajFpS01Jb3IraFFt
            eTMzdU1RTmw1Zng0ZmFLNHhOUWg3UVEKLS0tIG40Q0VLdGZ5d3JWK0RhcHZYZ3ha
            YUZ2YmFEMGlGa3MrSFVWUGpwQUIzWU0KIwm8wI1wl8zKwZ3bEkBIoCBh5my1JdGA
            Dojow6N3Lk9XegBLE44O8lPDf41/UfTriPw6EXAgOszLDIZjCF/niQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfa6hhdz9egnje3nwa2k0gpk5nr29nyvu74eprk20m7ql4fhw4esrlmt5g
    encrypted_regex: ^(registry_ci_password|cloudflare_dns_api_token)$
    lastmodified: "2026-06-17T18:00:11Z"
    mac: ENC[AES256_GCM,data:l5tSw/07rdaYmWIM9G5n48xuSGvUBuSzeLE/O59w/lNACbNfXa0f+itPX9PdUjCDv6dVs0nl8GkzVtlCNLnAWdlZ607TqknYM1I6Tx9yGiQ/nAznMeOS/xD8KyoOjwwOOJWnTcpPIpCM37WnLM3/8QBIWRTZEf+b/1WVaYL7yH0=,iv:PuF7MkKd9p+YV6hVXG5lVy+BcTYIhEczg7FNuJbWa2Q=,tag:70v+OojtmVgTkXfwy0q+vA==,type:str]
    version: 3.13.1
