registry_ci_password: ENC[AES256_GCM,data:dCcSp2pOCGH5OYLqZiMrZLRoegRGg7ZCPPL7EMFKe3Y=,iv:7Yf4XIrWosNDZXZ6HCdqYyvcvG7bFwjcD/SlbAZP698=,tag:Y+wQdW91d3XDFh8rgnZEJQ==,type:str]
cloudflare_dns_api_token: ENC[AES256_GCM,data:GEhSwqw7cx1jXP69dN4WH24krHgoG9V8edxpVlIl5LIPn6bGwab8ICq/GfpdJQ8o/U0iT3Q=,iv:n9sMt0l2ad8WWzXQf1CC/Oa/eymxTRdpbIE7ppWkxXc=,tag:ONWC6WreP91LdufM6IcTrA==,type:str]
registry_oidc_client_secret: ENC[AES256_GCM,data:BVXJTlQvjE5zddPU4ZgWGrIMOKRf0+0qwSY2+CsN6BMmNafcjMnaggTlUKi3V6Cj,iv:H77j/rejvDI154hbUzxvrJvdAOwNdvl59LvgpNBTta4=,tag:pQksVML+xsYk8NP4ZQL10w==,type:str]
registry_pull_password: ENC[AES256_GCM,data:J4sOyCQKOzElG8okh6ucQhJCnZovvWt2X8904LYj/8tgM+cLHy4PJE0MNQ==,iv:WfnivrXD3EiZKubHBbmC4MXWnrTwMhNfF33mg2VPgsw=,tag:Br8OKvjFHtWAvYXWKeiS4Q==,type:str]
registry_scoped_push_passwords:
    trueswarm-ci: ENC[AES256_GCM,data:C8BfvXZFeOlVBvDnikQTArsZQwSY+2ybv484HWIyoY2XSznykgNg7+Bv5g==,iv:kRGJ8FKxeHn0lyJPdiI6UcjbcGciAEqjq290y49y950=,tag:XMN9cQiAq3EyoaeoAU35rw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nfa6hhdz9egnje3nwa2k0gpk5nr29nyvu74eprk20m7ql4fhw4esrlmt5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSTlIYkI5SHFndjlaeVFS
            c0lBYkZvKzlIOFZOaU5BY2wvUTc3KytFWjNzCmNFdEJDVjF3cWRwZHdtdEVhNmFx
            Z3RobE03Z2o4UFdVcEt4OFY3T3U2aFEKLS0tIG95ODZvbHVTa3lYZGx2aFl5a1VK
            cjBpbCt4dEZFU2NNUFVQdUo5REViU1kKAjwReT9krrw0RjbXCVZV2YQQz0FlYEXG
            mXojBVH7qRz7azEDmz6RnaQq4yU/NXeRL0Eyf5ZeT/qwmH0pyVILfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-25T19:21:28Z"
    mac: ENC[AES256_GCM,data:Og7yBk09nBhmEUoEIsbo+LI8514Le3PeDo4nAumilRDG7wGVu+YgeaKGafOe+eXEOgVDvohbGbSe+VaCsc5im6pzdlKJLcPpvknFha2LYAvZ4SbolclY7h2Bx8DwGc8Lf/cXISCR0y53ZAohvgCfjoUO6mhK2faMHgdhYwqiiyA=,iv:ODKv4PErAcTTPAplhTA9bYSGTqJnk29yfRCR2M9/L64=,tag:8VKZKNottwoiJFe1UW7/dA==,type:str]
    pgp: []
    encrypted_regex: ^(registry_ci_password|cloudflare_dns_api_token|registry_oidc_client_secret|registry_sync_dockerhub_token|registry_pull_password|registry_scoped_push_passwords)$
    version: 3.9.4
