registry_ci_password: ENC[AES256_GCM,data:BmmrMoPbF19Sn9KeuqnTLSRKOstyAA7YHE3ZeS6xguI=,iv:rB+2dvmc0EWWeGM0fh7fWj2Q7FjD6saDH0RzHFegDDA=,tag:nwHLoEeKTCjRs1YL3VkdLg==,type:str]
cloudflare_dns_api_token: ENC[AES256_GCM,data:OVFObnofp8MZOwGBg4SBAEMjb0QMC5wmTbCppOnHEVVojp2KfRuSwDbu06Zx0miMWA4eu2o=,iv:9F5b0kD+fKzVCtHKcEmRQeiAWozmMLoRkALJMPilz6U=,tag:ifVXFkgvJ6rEz2xXb1JxgQ==,type:str]
registry_oidc_client_secret: ENC[AES256_GCM,data:Ws214YguC0jMRLKbp9Tkyjc43ycQeo7kKT0/Z8zOmHTajtXvY3DHBUs2Tc9r3EZI,iv:JobPs4FrE5EoQqIOV9zZ0qELew6n43dfXEyPwD0r95Q=,tag:TMYhXveAd9SQbqEUbXdHJQ==,type:str]
registry_pull_password: ENC[AES256_GCM,data:locey26ohNVr8DM8aNLca7qT6qbRHjwOG4aJyxV1zwrOEQ5WpOG7yxIHaQ==,iv:dtgo6DjQujfMxGPFWg2dM8auBtVS1IG3pTo4GByc4EQ=,tag:9jpjqwlx33yIeXdjUsOHNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nfa6hhdz9egnje3nwa2k0gpk5nr29nyvu74eprk20m7ql4fhw4esrlmt5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZ24rdjhraWJYMk9LbGQx
            M1RMdlJBNGN4M1Y4ZUZDWHV4R21xUitaZnlRCnlZVEExY1NWYThuQ2RtUmZleHRD
            cU9xWFlLemNFNy9pSGJ2NWx3ZzhJakEKLS0tIDgzSjFFeFkzOHUzWU9uMmwrUUs5
            bjBFck8rREpPdXRKUUx1OTFHUXVUUzAKVPvTeLLd6siPTWMD5IEa9fXAr2wUlIW0
            r1r9SDuagztyuM6++sMiy2ZaPf7HT3S4qpdFiGRniUctoyAURiQlPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-25T16:08:13Z"
    mac: ENC[AES256_GCM,data:olzEjObwBQNS75wEQw4ZTm1nLTuWdAOGmZ42Qpj2tOzJ89iA5iqLOqmeh+utizhrYpLUKHXsxtapja0/ee0mzmgL6n5MRP3r/ZOEmh2jQsl5oT2DhNt+7Idpgs17deZGZlpmUGqx+Ol5DdGz7IEUT6FqbhGA1zRiOJAoJb+1pHg=,iv:lKi5pWYbY+Tae5NOds7nIgBVSz2nRNalMh6lHZq1nig=,tag:RQ6lsy1heEmnVDdFHKP9qg==,type:str]
    pgp: []
    encrypted_regex: ^(registry_ci_password|cloudflare_dns_api_token|registry_oidc_client_secret|registry_sync_dockerhub_token|registry_pull_password)$
    version: 3.9.4
