reviewbot_claude_pat: ENC[AES256_GCM,data:8NNVjyDRK0++LiQ0vPDPp7VKLksGFOPNX42YWYfAcWxAiFfiUWfdig==,iv:PJxojJZc18L3NgCTD5Pj7naai1LTnv99fPhOB/5Hvvs=,tag:Qy4CgkI+nWc6d4zpsLTFUw==,type:str]
reviewbot_claude_webhook_secret: ENC[AES256_GCM,data:1rhbhYoZbRtuc/s+HpsQMRGwDqpU9zQN2AQpE1BMF8Rzdy4ojAcUXCa0AAWvulPXoKPdNrFfd5MbdrnZsb0JOg==,iv:93DudltXB7ucX9nToRkkvpKlQOGDicAclWXeXvPFVm4=,tag:oALydVvYWwvkuZDQPbQK7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nfa6hhdz9egnje3nwa2k0gpk5nr29nyvu74eprk20m7ql4fhw4esrlmt5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcStFWUNaV2xkajhLWU1l
            Ung5NnJlM3JrK1VzY2hrQWRjT3BlQlNWdEdzClAwYWNWYTNCUW5ZSWwxN0p4NG1x
            L2FnNTVzb1RLK2pvcFRsV3l3YjdQYWsKLS0tIHNNdDhQenU1VHZGQk1la0tLY3Bp
            TWREcnZJcVFPaC9ZWkpUN0xiV0lvUDAKg9LOIkiV5mDQUVX2tQASifhPrPIN3wF0
            /SWe/FLVdbedauaGuaUR4RDItxkjtqZtOloVbOAOMCd5Je/kzhmEgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-02T09:06:27Z"
    mac: ENC[AES256_GCM,data:wRUWp3gVVnq7Ja9DckWUHGdIUY8iAhq4aey+rMsve8DsYXvYIPmq6h9vbZqR8VOO7HuuuTtOTO5ZdCCWXCmFlaNFVXjbWbrojAfLacgMoyhHaNdBwmvFH+shbiop8XQ2YHEBO3028ktsIXKsAuF3tBazjSTeW+EylnNS+ch5eH8=,iv:zbi4RiiXXzfWAKv4txAfCr+q4qJHd6v4OWj9jxVN4To=,tag:2DOGJJfWQCwWY/qwwrCWJQ==,type:str]
    pgp: []
    encrypted_regex: ^(reviewbot_[a-z0-9]+_pat|reviewbot_[a-z0-9]+_webhook_secret)$
    version: 3.9.4
