reviewbot_claude_pat: ENC[AES256_GCM,data:EHhXgPrDVcp2GAwao9VCzc2mSW1xTG8VTecosz3U2udOLPaDL/h5yg==,iv:TkgDmGhIn9V0wQsZLancoD66ojdQ2GDYAryUhk0IVAs=,tag:qvp39TTRPs6c59QaYBrQCw==,type:str]
reviewbot_webhook_secret: ENC[AES256_GCM,data:dZ6w01IeOm+nA6JoFhIVAVBwAaIx1L6N6dg7sdfG9OzxiPV3Ryt7Hcrk3a0hIkPd3PWyclCWCitgUUh4/D5gow==,iv:8SykqB5A+qqAYunQzIlgYfUmmFEucS3wmGnnCVUT1q4=,tag:8ghj3A+G5sRlnU+6rXZGuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nfa6hhdz9egnje3nwa2k0gpk5nr29nyvu74eprk20m7ql4fhw4esrlmt5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ2J3Mk9QYUVGMVVML3cy
            eXIzN3ZodVcwdG5lVUVGYXNhOWdkZXB5Yld3ClJTODY0RGl5ZDR3Ky9DeVJkendy
            OW5iVlFNYjltak9sSDBxZ2loVlcrc2cKLS0tIGJZSnJubkphZElZdVd3eDZLS08y
            M0ZIZ3JLSjZza0ZLM3BuZHJFODNBdjQKD2ROSE19vYlGZJgnCO3WPZrkXba5mmDg
            C6FC3Sfv4Q/6+mCQq1nli5BTRVdyiDlMqqK/DljYILy2nzWUQYyIyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-02T08:26:22Z"
    mac: ENC[AES256_GCM,data:sk570Xq2ZyEUg/Ae6LsfovvlrkbJp/VG/qnYcb9QUPfwx30BLZdIA/4J03ZW8T6gZ9qLe/CsqI9/IsTdNfXO7fQYmTgdBz8V0gRCBA4Wg95veiBRfmXsXEEKu11Q/yvSmCOEJHYz2sfY2hpMiCiFi+60glokIRVbjHDWr8AOlNk=,iv:pFtO3+yIQjkU0meY+Fauv38o4CYkmUmin9+KuP4eFzs=,tag:Y9G7sFObW4Vfp4Wx4pfq0Q==,type:str]
    pgp: []
    encrypted_regex: ^(reviewbot_claude_pat|reviewbot_codex_pat|reviewbot_webhook_secret)$
    version: 3.9.4
