reviewbot_claude_pat: ENC[AES256_GCM,data:9pUPF1SVdICF+C5jYdbEqW0uG5Y1n0eZGSYWCfftFA5Brx6sh1spVA==,iv:nktiIkOQlgDAfhA/rfHBcN9ggW6aui79dwwRJ9BL2fQ=,tag:dXYGmiZTLTjpzQnDjtLwIA==,type:str]
reviewbot_claude_webhook_secret: ENC[AES256_GCM,data:U5sqf3V/hs6ms4IX6nOXJF4ClBmmFXQ6reTUqXe8AU1aMWHcazgpjZI0gES9JTciyd7ssNzWUOxDb2qHHDV65g==,iv:UciJM0QkS+vaRHeEq7I1aSAKs00F+MnlxRHz6g7NAZ4=,tag:fybqu+BnR5yYMsubh+wJIA==,type:str]
reviewbot_codex_pat: ENC[AES256_GCM,data:SPwAtHTyrwv88RERJ6waT7BSaJMww+Wmkjc/emnWtZPZkITxL4fW7g==,iv:I9QfiZY3KvnZYqAWp9FyjqhOekwOtApaLpbN8uO9oWw=,tag:5BTUwBUejt6AiwK/ZinxXA==,type:str]
reviewbot_codex_webhook_secret: ENC[AES256_GCM,data:xK/c+hWs3FVYGh7OUx0C38DdkiGcswmvfpI+zFXGHkz0vQG7wZrHuel/IQl6F/obNKaQEGGmPAO6zVwr/ZCnSg==,iv:dvxDM5YGy6m3qj4pniUNO98QExinhf9joZSksFfvlzI=,tag:Wrz+V5I3E+i8v9SVrRqe5A==,type:str]
reviewbot_hookcheck_pat: ENC[AES256_GCM,data:FtWkPgjcIBbk/WISufyHmEtRUeG6hB0SR3dya0Acqj8xB1KdpJ1IpQ==,iv:6SjVT5ouWFRUMGqRUWM6WXasEpqRGhAmABZR/UT9tiY=,tag:+Eg9bbaC3+MNNmBx+sV48w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nfa6hhdz9egnje3nwa2k0gpk5nr29nyvu74eprk20m7ql4fhw4esrlmt5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MkxiT1AvdVI0RmExUmR4
            R1lob3JjR0JDT2IraVE4UzVvZG1SSjVJVVVBCnpFcERQRWJTSDlaQmNldHQzTEF2
            Lzk5M3FFOTVlVENKdk9mVkJ2R1VZbVkKLS0tIFpocHgzRGc2SGYxeTVhWTJSczRO
            aVYvZmViWmtXS055YlJvNWhMZXlxNTgKGK9dBB2+ubkDWfK1XVDp6DYEeIwswm4d
            WrDbGL4wZ3CgS75S+4WT9z8O2CfgoiihgbB1Rdph6gzedtFF8Azfvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-09T08:21:29Z"
    mac: ENC[AES256_GCM,data:lXhL3g0ps58J8cuHlc0/ed6G/yIJbBi+DNDDW0VbMGZv04gerXV9ecGhIx0j+gmtvXi72pBZBEpwGfAXPilah7Lw6s0KeNQqOiyrI56Rxn0OWhgPvrexUeYg23TBZBYzgIBb9nAygiPcyDG3dh04wq0NhVJnQ3c6liq9VK/ysNo=,iv:mEPY9QW8FBteu0/dGKmXvvxyfyGS/OsKwdgWuQ86XPM=,tag:V6hIo1bsC/Zh3cObkw4Vqg==,type:str]
    pgp: []
    encrypted_regex: ^(reviewbot_[a-z0-9]+_pat|reviewbot_[a-z0-9]+_webhook_secret)$
    version: 3.9.4
