apiVersion: v1
kind: LimitRange
metadata:
  name: defaults
  namespace: gatus
spec:
  limits:
    - type: Container
      default: { cpu: 200m, memory: 128Mi }
      defaultRequest: { cpu: 25m, memory: 64Mi }
