apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-homepage
    namespace: homepage
type: Opaque
stringData:
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:MVjLmNee7J1QgGqc8bFHWGYPnFdewmYLPuHSJXpHj6GrR96R2PeHI6W3OydDgBkzMcEis/s3HleYdZBzQ3WH4A==,iv:1SCzc9cLTj37tID7+OAmjL6Zd3yBD/vJnVqr03IA8I0=,tag:mZ5orU8uDUkVDyT3tsOImg==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:o0xyWKZlo7erEU7SO6yflqGL750XIiKY58gpAL1VQJq8/nh+CbDbPmRGLfM=,iv:m4Qea3SR/nHyMZEkVkHMTocmwFk2btQvDNhlGWXLD0o=,tag:dLIgfVI2tI3Y9Ef5bf7O6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNEU3d1FzbG1GNFhKdmM2
            eU1YWXZVdVFQRDBTcmwrdEdJanovZ3VTNWxBCjliNnlBalQ4RXhFbFFjZVN2RThq
            VUhMWkNVNS9XVTVXRVBZL0NxaDBjSkkKLS0tIHcyOG5IY3pvekVOc3FPUy9sSG9Y
            aU16azJScjBvaUxiRC8rV1VGVURLODQKdBdj8wIeLQSs3jxOM837m3pCysRuRwnx
            bURlfErUHv2a6etlxSuH0vw38+x01VHqY9DUiY/ViWOcUjI/8FX+kQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfa6hhdz9egnje3nwa2k0gpk5nr29nyvu74eprk20m7ql4fhw4esrlmt5g
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-16T06:04:54Z"
    mac: ENC[AES256_GCM,data:jXpX0pDSZBSq7Be26gsyUqJt5wN2rPl0ue5KYS3f4sEyOwBmPZMtNUyIe5eq8k2gUkZza6APPCdDnIl9VxA6k6MBn9q6K3jNcIQYHua4s68XJUMGy9r/8MXNrkMO+fVpm+fxDSEQSX3BBNqvQLA+SaBs9Xy5/y2X/y9m0xLRcG8=,iv:iRWjw6OmKac/z48T85E+amlIpcC8G0yZMb2GU3u7BVo=,tag:8lA/UcuW69Zflp+1UfMaWg==,type:str]
    version: 3.13.1
