apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-homepage
    namespace: homepage
type: Opaque
stringData:
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:MVjLmNee7J1QgGqc8bFHWGYPnFdewmYLPuHSJXpHj6GrR96R2PeHI6W3OydDgBkzMcEis/s3HleYdZBzQ3WH4A==,iv:1SCzc9cLTj37tID7+OAmjL6Zd3yBD/vJnVqr03IA8I0=,tag:mZ5orU8uDUkVDyT3tsOImg==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:o0xyWKZlo7erEU7SO6yflqGL750XIiKY58gpAL1VQJq8/nh+CbDbPmRGLfM=,iv:m4Qea3SR/nHyMZEkVkHMTocmwFk2btQvDNhlGWXLD0o=,tag:dLIgfVI2tI3Y9Ef5bf7O6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3R0VSRDB4bG1uNHJNMXdt
            eDBLQ3o3eXFkSW5VTmpRTHhHT1IwM2NudHdjCmJEUU94UG9iK0M4SG50VlllYnFB
            VWx6VUZVaDdNb3EvMkNOWXJYdy9wbUEKLS0tIE43VVhrVi9HdzZjZzdmbnUvZHVw
            L2VCazlUUFk0VE9RemNiTUJJbFg1NmMK34RjloYZ+8rNeNN56mLHAWtyBF5Vyo/W
            9Nva9lTXIscYOIC1G9UlawWf5gB0axtukUXPaaGFmf1zSnY296DeKA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfa6hhdz9egnje3nwa2k0gpk5nr29nyvu74eprk20m7ql4fhw4esrlmt5g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbGg4eHVSWGE2eCtrVE00
            T0JFajl2VEtEVGsvU3VVc2Ztbm1xTEdyZTBnCjdXODE1TXI5UmxhZm5GUW5VeW1I
            dFBrbG9iN3YzRHd5WkYzanJ4cXFDRmMKLS0tIHN5WlpGTTY1bVBPbXVpbW5rU3JY
            WWt6ajJkcFZLV2djcEVoUVVhbnhhREkKmJuveMXrL7d/mOyaHKeeuJZvqY2dw63O
            oEOZ9g5wE6gytFm3pqUvjfLddwdlONW4YC9UwSfgSyT/5c7ZvBKtXA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g0exjqgq9l52m8g7hqkqelc3kcam4wwlkngzjhn5wv6dzxfjdceqdyfl4t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-16T06:04:54Z"
    mac: ENC[AES256_GCM,data:jXpX0pDSZBSq7Be26gsyUqJt5wN2rPl0ue5KYS3f4sEyOwBmPZMtNUyIe5eq8k2gUkZza6APPCdDnIl9VxA6k6MBn9q6K3jNcIQYHua4s68XJUMGy9r/8MXNrkMO+fVpm+fxDSEQSX3BBNqvQLA+SaBs9Xy5/y2X/y9m0xLRcG8=,iv:iRWjw6OmKac/z48T85E+amlIpcC8G0yZMb2GU3u7BVo=,tag:8lA/UcuW69Zflp+1UfMaWg==,type:str]
    version: 3.13.1
