apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dsh-acceptance-workspace
  namespace: dsh
  labels:
    dsh.chifor.me/acceptance: "true"
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
