apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-searxng
    namespace: dsh
type: Opaque
stringData:
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:2CGsfM9M4z6qR8d5Q6ATPnx3NR/d3HCLlhOLW2Cxh1sxJt4euPk5br9bGA30QGEgrw88m8a3Gf2KY8qusprpAA==,iv:SK8MBEZCbCtxSPfWqIoaZC63PXR6Z4/41LwIj5mec/U=,tag:tzTabjasP8UiLDOjrtgjRw==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:/N9EHyfbB1iu9Rj7ZvRHqOJ+Wp8GXd4whS4ebdhIZ+tEmoF6R2X3tiLyCCs=,iv:W9k6yd1ZlTkVoUpq+t+ui4LFhSqBJ4AsGpDIUbemTto=,tag:l5zZjmz1Y1TJGOIe4nqMyA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSTZtVzZRdFhJT016ZDJU
            eEZQaVJ1SFFvZ05wdUh5MG5uRHBvckNzL0ZZCjFjMkxnWDFEZnc0RGZ4bTlxY1VG
            VzRhNHcwZnVOZVduYjR0dVFOK0xnQkEKLS0tIFFOMjlQSmxReERtZDNiMk4rSTBu
            ZWllUDM1RFplT0VGczhOZiszNVlnTzQKZaqBZ4YmwMM5hBVtV2A4z3i6Inm/y4Z/
            vENdIrPTLgdn6wQduN406ZT4VbfrJpWZNVIi2yIpn93kOdDGXY138Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g0exjqgq9l52m8g7hqkqelc3kcam4wwlkngzjhn5wv6dzxfjdceqdyfl4t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T21:33:22Z"
    mac: ENC[AES256_GCM,data:Li0xOwIn+4Q7lyrI2aJFJOvIC5UcQsXo4wOczXSAltTxJBCGyDK9AchZ8qizcNd+O7GqftKNyqfyZfbvmSHGuAQEld03he/+eqUY+Q3n2rHqI3RZEXxkaM+y3/2wR1HYpVJaywwcfYt1PODjeM3bHZRzU9daUE1uf3x32vsDQXY=,iv:+JG9t/hX3n89b5gbNs327IWH6UDBkqgse5SVEWMtHIU=,tag:EI34Ip/PrgO9kegpUgTx+Q==,type:str]
    version: 3.9.4
