apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-searxng
    namespace: dsh
type: Opaque
stringData:
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:6UJKzp6PwafshOpN3PoL6XI97kCuf50ApcK79kDj9a6R8EgC8X7+H706MXvJpeQFZE0aAkKZPTf/tUeC7Q1CvA==,iv:SK8MBEZCbCtxSPfWqIoaZC63PXR6Z4/41LwIj5mec/U=,tag:l6KgtkPe3K+EZYRAxyDvVw==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:S5jw28o8WJiqLY50uzM2MKUzLRQfW8dT1VdIA94XTmYpHCDWAcVQsqbqpvA=,iv:W9k6yd1ZlTkVoUpq+t+ui4LFhSqBJ4AsGpDIUbemTto=,tag:8oXh4mf6p2OTTFv9aZa0bA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nfa6hhdz9egnje3nwa2k0gpk5nr29nyvu74eprk20m7ql4fhw4esrlmt5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRkFwbnVtazJjcVVYc1dN
            U2lXYWdDa2p5dUprdTNhMVI2UjNqVFpiQnhZCmpZTFpzOWswaVo0Smo4Y00wRHJv
            a0dLWXhJVzFLOUo3SU5OL0x5Q2dKSG8KLS0tIHlVbFVmbEVOamxzalRZOUo1cGhx
            T1N1SHBXYzRaMFZNcEtRQnpmK0p6S2sKjgcn66+ShO8tjUpLiiFlUZSs4PfYDm9l
            L8DG9XeaxKUpZ9Z1k98gj2uiWa8XHK7tPQcklpsYcHqMd9vI8T3SnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-12T06:55:20Z"
    mac: ENC[AES256_GCM,data:c4hEjZ8nljNjGGzTgpCpaGw1UwjvxXGesIxOjms7sNcY7vpL65x7ZB28qwWyE3y7LLAry22HaSmC4SxcDURw9e1gbcb6wNUfHobWuYOzZPm7mFa1E1QTxdpl4y4KEDNQXeWqW2yKEq8k0aVoTZBQ6yvGN+O5j5vZPlg9ESBpbQc=,iv:i0ACJHEOEF1EdjTCly3rfPNE7Eet0Clh4WzMXVysut4=,tag:pCnmY1RiKa8RuQ1jtVnQSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
