apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-searxng
    namespace: dsh
type: Opaque
stringData:
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:6UJKzp6PwafshOpN3PoL6XI97kCuf50ApcK79kDj9a6R8EgC8X7+H706MXvJpeQFZE0aAkKZPTf/tUeC7Q1CvA==,iv:SK8MBEZCbCtxSPfWqIoaZC63PXR6Z4/41LwIj5mec/U=,tag:l6KgtkPe3K+EZYRAxyDvVw==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:S5jw28o8WJiqLY50uzM2MKUzLRQfW8dT1VdIA94XTmYpHCDWAcVQsqbqpvA=,iv:W9k6yd1ZlTkVoUpq+t+ui4LFhSqBJ4AsGpDIUbemTto=,tag:8oXh4mf6p2OTTFv9aZa0bA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYL2xnbHhVZHJRTDJpWTFG
            SHBiTlNLZktDYU0rVGdNQzF4NVkvd0tKa1ZZCm9TM2MzdERwYVIwdTlvTnlwOHY1
            ZWtTc1pQYkl2akMrVjVPZUI2d2YzeWsKLS0tIGtsMS92RnhUbWNaZmxWMjZ4bmw5
            b3gvMzUyK0FvcWlQUG9MUi8weDBIY1EKU/YMxIEp6huA+kK0sbX4QmZTqpE4yBI/
            M0XsVcWpJQMlEvdwHux3cz58b7TUgXNLeltUX0nNS5Zp6FZ4vthZfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfa6hhdz9egnje3nwa2k0gpk5nr29nyvu74eprk20m7ql4fhw4esrlmt5g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldy84aGlPOHk4MTlRdDhB
            REs1WGx5TkMvaWNJamF0a3RIOXp6ekpJcmhrCnNFOTJUWS83Y3g0WFM0YnJ5MWFH
            OUFzY2NCTHgrZXpSR1FRektORnh0QmcKLS0tIDFHUDJ3NHBrTG1iMEQxNFQyVXZN
            cWxmbkYveDc3U1BNUjJpUWYxOEJBWE0K4WC5aPnKYJrNSO07sdOdvZdQvERn4B1S
            MaGIxjeeTBF5ZFY//fxcm0c3NCDtDXY/asxV2FVnrMRetZ0UtuSqLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g0exjqgq9l52m8g7hqkqelc3kcam4wwlkngzjhn5wv6dzxfjdceqdyfl4t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T06:55:20Z"
    mac: ENC[AES256_GCM,data:c4hEjZ8nljNjGGzTgpCpaGw1UwjvxXGesIxOjms7sNcY7vpL65x7ZB28qwWyE3y7LLAry22HaSmC4SxcDURw9e1gbcb6wNUfHobWuYOzZPm7mFa1E1QTxdpl4y4KEDNQXeWqW2yKEq8k0aVoTZBQ6yvGN+O5j5vZPlg9ESBpbQc=,iv:i0ACJHEOEF1EdjTCly3rfPNE7Eet0Clh4WzMXVysut4=,tag:pCnmY1RiKa8RuQ1jtVnQSw==,type:str]
    version: 3.9.4
