apiVersion: v1
kind: Secret
metadata:
    name: backend-qts-secret
    namespace: trident
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:Eas=,iv:UhQ4n10porqdwJ0doHqxOfOhaG6OpyRa55U7mi72Inc=,tag:+4jA+frxBYGsygIXxB4Fkw==,type:str]
    password: ENC[AES256_GCM,data:S0xtNngWjZzmszee9ec=,iv:EIo9naqQTHt/alkN62SMtevWF1l+0OJYQF/N51KzYys=,tag:VxoDW4tuJMxvM75a6tFEzg==,type:str]
    storageAddress: ENC[AES256_GCM,data:6scFyD668hjWybU=,iv:r58545/Xpfe0ZjvJ82SL64AzKQjI+AO8cCvnjuVGXhI=,tag:xRmiEgIIUsebvqZGF9Aveg==,type:str]
    https: ENC[AES256_GCM,data:J+2PYf4=,iv:4eFsFlKcQjg+CTB0p2uIJhAKE6RJkJa6Zc4/voVNHM4=,tag:rGDNwFyY71fXEKL1GfMKtw==,type:str]
    port: ENC[AES256_GCM,data:bri2Dw==,iv:B2YySMbxfDGy4Kfq9+WAPdOOy2+t7z1svHjN8MH425w=,tag:q7KwRYo/Si2jb0UqoSGtug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiMjJqR0RkMHZuNC83Q1Nz
            cnd1MkVxTGsrZXNKUEJxN3ZGTlJUU1U5U2kwCnRKejhKUUtZWG0wSGNxbG9ITzBS
            MjhsY2VENU9jOW96dDlSOUJlYWxuT3MKLS0tIEFMYU1DaVhqa3E3YkZqcHFvUjJ1
            cFBMczg3N0gvc3FjdEt4KzJCWmdxWmMKZ73Pdl11OZemrOJgq8/gp0rALpD2IP7G
            bJkD0QRa06vKMMjZOL4Mf5L3C3X99KwqIhWYZQaEkSU0BTLnH4ezOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfa6hhdz9egnje3nwa2k0gpk5nr29nyvu74eprk20m7ql4fhw4esrlmt5g
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T15:35:27Z"
    mac: ENC[AES256_GCM,data:kOSt1VqKZfHLhyYtuxR4T3urchNP2QpT/fygH4uE4qUV+ElTXHTH0c4e1EeHAXqNUB/JLwb8uXEGTraZbpGEHB6d/srHDlezya/T36Ce2pkpO9iaSn34OBAijDodU0Xu03iyP14lRXcE/BVNOpSnuoB3DO3vuLTxN3jZqHJqEpI=,iv:qRzp7OaIx/umPNJwXZGM+uBK8NlfURPDdOZLxw7AYi8=,tag:47WlUhDunoON7QN6JLpDBw==,type:str]
    version: 3.13.1
