apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-creds
    namespace: edge
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:044tRsGPQVLxVulakeO/rb4hWdi3AUQzZZVKAE7aMA33G6T1evYAN5mHaWa2D0pXP72MZpJJ6GSiGyF3H6Tvh7Mtq/bw05ua6KbQYLGynZwt0vahM2fPZv6l7dGUMhtn70mnvKDxTNTJl4rDPdGXDYsttTrXZA5ha1lZOUZSwC0+3vyJttADhjfblXBgGBrC3ZjIq4Wie6jOAPK/ZqCdWSIL7OpJ9hXRIi207iCmgg==,iv:l0Twk30msrMsKR51i2Kd1fVF3FE1QK1+RKX6lqNoadE=,tag:4o2euJ4XjsSVIR/L1DjUqw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcHZvKzcvQ3JOQWJ1WTdK
            QkMvZTV4bXdmT2h2eWdBYVc3cmJBUng5L0RZCnVSWUlQTVZxRUt3bmp1ZXpqdjc5
            Z0dyZmRaM3VpeVdIYlVjaDNzbTFWeVUKLS0tIFk4YnJwS3FOWXhxeFZQYlZ6bUJG
            QW9wc2JpcTAxamF6NCtpeTB0VHVnZUUKcY/W/4JCM50yjgf/k7U429s5IcVzh8i3
            xnJrwoBjKy6tVl3JkE9p1s1xcsA/IM7rbK2acWpuwpZbZ45Z4l34Sg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g0exjqgq9l52m8g7hqkqelc3kcam4wwlkngzjhn5wv6dzxfjdceqdyfl4t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T21:33:22Z"
    mac: ENC[AES256_GCM,data:hbYbs7J+i3VLPxFgyqn+0v4VMYlVAvGOn2teoaW9d9XrfJxUvZyamWLnsQKOO3ZlDShd+Yx2SUpuAPIE/JKUZPQbKVbtRp9ppm/cZqq5hZthETSqfEcGsN17AfbQh+c3LS2oRXGpRaAtL2BibOYnQsHokQ3TJK+xGCFaM1CTmdA=,iv:OqxoFUPiSlLXIa4wQxlsG3VtDZ6WggoebyK4x7XkxeQ=,tag:kD10Rj40xOfphvnuUdjIuQ==,type:str]
    version: 3.13.1
