apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:nmw0UztS5zwYLUS8sJAwppI=,iv:V/8GvfY6a3I8nTH6lOOMuJKxgi5NOsBUvIguURuH7Lo=,tag:NEmtl8HpVAlPlGfALxCiDw==,type:str]
    client_secret: ENC[AES256_GCM,data:9eyu3I9iiftOo5bMkvraXODwxItUzpudClkrjN3x0FUTyWmiebSvuREo0AUhu3WcanR6lSc8svLrJH7A5bB4og==,iv:LxARcCprtUGqhCxDVYxxUHmVnt9/W7cCSPd1b2h6qBg=,tag:mUEma08ev4hiNeTgnbK4bw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYytiWEtnVzE4UERXbUpv
            ZXE5cjhSY3Vzc29FUnhnaS81aW5NTmRFZDNRCm5uVFJTT3hZZ0ZaQVhBeldnbENw
            VUc0UEJVL3d1NUkyUW1tUkdWcklJL00KLS0tIG1EZlpuNmxRTHY3clAreEV2QzdO
            OGxBcjN3WmdzZHZNazNrSlhCUHZkcmsKqfPD5QzJ/v1mb71oPihxfI0F/OGrEzwr
            AtdhLUPz+ydNyXhwRj611sJDKSgMyZ+tDIrHEvzpcr5AIJAYVv3dJg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfa6hhdz9egnje3nwa2k0gpk5nr29nyvu74eprk20m7ql4fhw4esrlmt5g
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-14T17:42:24Z"
    mac: ENC[AES256_GCM,data:7VkIJLosgtu75wtLfwIBExHNDMwxXkeUWOgDxSX32DwRhe4JsQvTzstoLFgXG6q4r13ZYgT6uva5D1Q9gEZp55gMXFhxN41zuhlJDhO1TCFXX9HlDj4EK90xI/WuIIgTDGy1WtTB3ZI0f9CEOEg6iLxe0+coQeNnHvm5SuPvrSI=,iv:pXVWnkzMVR7jHxq55tSSE9rm6s5Lr21ea66AWOL0izw=,tag:CY5v5IVoowFG6aCjNPwqPA==,type:str]
    version: 3.13.1
