apiVersion: v1
kind: Secret
metadata:
    name: ci-rerun-watchdog-gitea
    namespace: ci-rerun-watchdog
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:Gt6TSavl6SMXdvX0wPv7sLJ1FRHvdo09gzqsiAL+DIljQokWY8vInQ==,iv:5PlBn9FQQwgX1DqyPtqJ5dcvWE1GKA8RRnTcUoAH7A4=,tag:yJZwE0Q9vg0k92XosP7AVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrM1hPUElYeXhRMUZoNXZ6
            ZllGVXBHUGR6VjMxWHdaSDF6aks3dm4zM1VJCktGYzMwNk5NQjZlaWJkK0piNHN4
            ZFA1SEowT1ZGUFE3Z3lKREJ1Mlo0S0UKLS0tIFZCY2V2OWc4RjRKaXV6YURoWUhP
            RDRHaGwyR2p1Y3piaVd6aGM5SlVYYXcKIYdUugL4T29NfIdKeip06fBVR64OtDbH
            BY6gbd2zdRThPb9zHAj3t/V8s7CQItAS9t0eP9AY30Ux+PGDYUihHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g0exjqgq9l52m8g7hqkqelc3kcam4wwlkngzjhn5wv6dzxfjdceqdyfl4t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T21:33:22Z"
    mac: ENC[AES256_GCM,data:fkyjU9vHPOraV/bqyPJP8uruAoSCJuf/eYFSYCqMjoZyJLZ0zB5nU+G+n/I0t2nVJF0wqN/NEEhk/eAJEEOB/rQ3b6o0OyRztRyeLC+i52aHYmaVR0mdvNLgEr9bPrDb57rlhZDS8wF072JzthJVTOo0x9cp74mrQZMke0yJXno=,iv:ou0QP/023ucEZOE6yI+Evpk/C6nBw9/WGAN+VoryJCc=,tag:5DsxfdC/EvBY6Snpzi2tyw==,type:str]
    version: 3.9.4
