apiVersion: v1
kind: Secret
metadata:
    name: ci-rerun-watchdog-gitea
    namespace: ci-rerun-watchdog
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:GvWYXFJnlfq2pceOVzIgMcjScSeGS61/yGPAw3H2NBum94w7+2efFQ==,iv:5PlBn9FQQwgX1DqyPtqJ5dcvWE1GKA8RRnTcUoAH7A4=,tag:Sij22PIiQir8ynTdElUehA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBOWtCQzlTMm5tWnFYbEF5
            aTUwY2pLa3pRV1Uzb1NsU1FjbGY2K2RqWldJCjFlN1R0OStuaXY2dWVoTVBVU1dH
            di9UYitrYmw3TTBmOGoyYi9FQkNNTWsKLS0tIDhuSUgrTDNRS3lYWGVQcldOa1R0
            eVVsUTNsVTVUVWdHbHhITGh0Q3F5MEUKf8J6vIQ11ChwlO+2ydFUdyGuB5WbFC71
            XXLTeZ6/atOzI63Aa8plZ4QKuNt23JXjwZkPTKBno7VIY/SPd7dooQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfa6hhdz9egnje3nwa2k0gpk5nr29nyvu74eprk20m7ql4fhw4esrlmt5g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dWZtSklRcW15eFlQZ1pW
            WVljSit6TnROeGdZcjRicEhVTWRBMTAyVGlJCkZBenR1MlpjTjFlcFloRXNMaElo
            bEdUdGk5MDlJL2graHRTTDZXVHVrWTAKLS0tIEJlZWdSNG1wd2lmRjFRZVcrVzRQ
            OGNTczE1TkxpR2djanMxZXc2dzFGU3cKSpvyZqlBdTx9GINBvjQwg3SKQCa8gCOA
            DF3OL+A5YPUGjvDSiwkYisdz1p+8o+/XIcBWOcJrFMQK+2eFO4r6YQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g0exjqgq9l52m8g7hqkqelc3kcam4wwlkngzjhn5wv6dzxfjdceqdyfl4t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T14:14:55Z"
    mac: ENC[AES256_GCM,data:8rM8B2E5iSgOsjk1oy5ZBhKMzJ8Nt4ZCdkQFHh7VEV7py7B+uG8w7SGtgMJMVTqK4WHmsj/+PNwlMAP/voY90FSG+cbo8kSrWHfjd08BEgcqZG6j337CNv/PyHwUamK07XZsqZ5sC0AMgg29b8WpaJzR2go4jfo6Tm9Uy+/QBJw=,iv:it5fb3kT7bnNhOhqfw2zS/+VLh5yAIdW+XMJXSKxdNI=,tag:7luPfTgWqt6UMnXaJHvcpA==,type:str]
    version: 3.9.4
