apiVersion: v1
kind: Secret
metadata:
    name: infra-pg-openwebui
    namespace: databases
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:VGQ/gu6P/uC9,iv:CWylxflYIPa3q2mktJKwNqbkqSnP/XrC6q957Ch1LfE=,tag:ijvczBH4UALTlHr4ejmyOw==,type:str]
    password: ENC[AES256_GCM,data:cRnGDLigPCxSuKReZBd+1K5Aocn4yPRQvGjwf7bFUo1jV1nHrnnL2w==,iv:iF/24g9W9hPpIPRKBcak1e8idBi3p0WczH7dhVfL4us=,tag:leZdKmzJeDblnSVcSxb98A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRHRNYmZ1a1ZLOHpWWVhK
            V0VlRFk0Z3o0Y0NXamNBS3pZblU4eVU0dkgwCjBHZ3crTFpuYlZLQzlZeVFGcnZD
            YitwdHZWczgxSy9GbUVobW83NURZdWcKLS0tIFZTVGhMdWorMWVTR2ZBcEdmRlRE
            SHNKQWk1K2NGMmwzNEpNWTg2MUN1VmcKcimQ/dHqcOzmWD8DYThycpas5X2DUJ3B
            SeSTXhlRL+38N94c98iXpX8mUFiPDhRHSQft3X7s2kaMC75ENTrYHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g0exjqgq9l52m8g7hqkqelc3kcam4wwlkngzjhn5wv6dzxfjdceqdyfl4t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T21:33:23Z"
    mac: ENC[AES256_GCM,data:F/+d2j3Dyknk1gU59SIhLI88+qUN/C/o66PRyEmqzDehEhTLJ2FOm90jDuE7izDzU1HrqB41kt2/ZqzPUH2JXs0y7jS8o0WPvPHyCZJjADekwXBC3Yq6jstxD8SAIeW+NnK9e0UBlqq7I8F+Hd6mkIaakizl377cYmKfKkBoumw=,iv:DxejTgHNw8XVoMw9VP1YSiK9Y7pOQVXQIxbc5VjTXAI=,tag:ojas+UpZzV871vep4RVaUQ==,type:str]
    version: 3.9.4
