# Credentials for the grafana database on infra-pg (initdb owner). The same password is duplicated
# into monitoring/grafana-db.sops.yaml for the consumer (SOPS cross-ns duplication, repo pattern).
apiVersion: v1
kind: Secret
metadata:
    name: infra-pg-grafana
    namespace: databases
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:prT+KPrAFQ==,iv:oEqu3QgFVUoR0VSUGrLHHQABe+Zho/Wody10cGum97Y=,tag:4HEbQOeg7z7ZD9VP33d7LQ==,type:str]
    password: ENC[AES256_GCM,data:I8MbnrJcwBnzVwZ2MRgTDHsZrXOnEpLwRO/+jZ4J+m1oymmv3+YGOuCaVdCCcUkH,iv:jQQbBU1u7FwMGBU2LgsXaIs44dFoGhxWTV2L/qfhGFw=,tag:4xGlTOaX35AA8ffozY0MVw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYnNHRXF2dkt5cFVjQTZL
            VFZRNDd3MnBEangvNHVEeFlqcmdFbjNabUVVCmNzbHcrNFdhTy9yMm5sL1A1Q2hT
            VllPclVBV3VVRVFOaHA2MmFrQXBrR2cKLS0tIHpBSEpJOS9iQmthb1hIOTdTUFZS
            YXRwd0dKbUdUUm8wdkk0ajVUZFUvemMKejyj0ZCpFq/5AMoAAXtvTn4933a3y2z2
            MPo0jd3ry4xmBLp0XqkL3WT4yWxq2N7YipuF0kzOyQ3MJC1eTA4HXA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g0exjqgq9l52m8g7hqkqelc3kcam4wwlkngzjhn5wv6dzxfjdceqdyfl4t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T21:33:23Z"
    mac: ENC[AES256_GCM,data:cnJO6avdvMngt0xkcgNraMPI6On/ocBPwLqJjfFqjPIikCYN1dMZiPzC+AR0+gE2ZGCmAqBoXiZUVHuvxG5ZxQNvVYivIxY7HZcQjU/7rQPnqNjeGJJFJWB0B9Hg5CII/xuMBz7XX1FGQIU93lnLRhAUyxvbKG4aKTgfnPESmvk=,iv:yyTOvjjof3HEtGSU5MjLgTmbXknrMG4GwlZbbB/o4KA=,tag:u9G/7r5J3+p9T3UR2hl2Jg==,type:str]
    version: 3.9.4
