apiVersion: v1
kind: Secret
metadata:
    name: infra-pg-agentforge
    namespace: databases
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:iHWBD4yTbbm4oU0ViPddVN/GDQ==,iv:aQXnZ42agi8PChQNf0NSqVay97eVVSRoJiPdqntR1bY=,tag:PNhEaAlhRMFbn0U8AAhJ1g==,type:str]
    password: ENC[AES256_GCM,data:mhQSU+f7OKgGhoj7DrmAiYoLcJxqlDf2+cs4yqDNzysnoeAZL1Wd/w==,iv:JmDFzau7qSL5GIkQKQ4oihulmNAP7FW9pJZUGsDfuTM=,tag:ggNubdqIqCQl98DFS3XspQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0OUlQUnJSQlByb09pM0dI
            bkFBcHpDMVc0RG5BOUY1aWlJUlIybWtmNkZzCnJvRnRlNTM0V2MzZHU0L2pSWDc0
            MVRwalNidXBwNEt3QUxhUWVFSTRuck0KLS0tIGk1eUQyd0VxOUdkbTF6cXN5bEVN
            SURaTU81QTloSkh6am9JTzFWbGdjMXMKEKVbpi/PX+HN7bMbgYvK3smQ04jG8/tx
            rgogBWliWzalabju24kUzuHbCDJv5YMToWkpFkCUKigXRW+jnv/sJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfa6hhdz9egnje3nwa2k0gpk5nr29nyvu74eprk20m7ql4fhw4esrlmt5g
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T13:04:10Z"
    mac: ENC[AES256_GCM,data:wRPiAMZaDy3an58FCgQg8oo7bkb7wQLvBHPpIGUGd8KAY5HamhsuLuO5vAo1q0v6S90vMKrtbeKshaLmEY+rFH2jkkGwWaihvXDLo/DxudBGtOgiSsYj3Nmjbd6bSt1zRRB4CqwZz1Mt2fVIXj5UxqsLl3VTWWjv3io70s/9rW8=,iv:328nByAtCJUbfEjoceMGHRHK9U1PxhGXEV4YOdsgcVE=,tag:Bug4dcLho+MKvCOSAnOWCw==,type:str]
    version: 3.13.1
