# Credentials for the authelia database on infra-pg (managed role). The same password is duplicated
# into apps/auth/authelia-secret.sops.yaml (storage_postgres_password) for the consumer.
apiVersion: v1
kind: Secret
metadata:
    name: infra-pg-authelia
    namespace: databases
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:oUW5WWr4fBI=,iv:SePCB0XXAnUPpSdM6YHJPdlvw8CsdUe3kW2qsC9Yw5I=,tag:G+TvQjmHttX60YnSnvwleg==,type:str]
    password: ENC[AES256_GCM,data:Mod2RcD56a4/IRjKxcKNVNH9MTz0LgliqbBNLZs3oc7UEOPeIXVyZbCy5DF3rcoc,iv:iMIwjqLxQUXfPUm9r80LdXXkti3h8mOB//7xyN1tZfk=,tag:Ju5BtCE0a8z3PqEzyQZSVg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WnZnV2sxRHE3YVFTbjhW
            WlI5SWNPaEl2WjdYSlBydmVkam02OU50WEFNCkttWmlvbVVxUU9qaVRzZEhiR1Ax
            d0tvT0VQeCtuWmh3RS9VL3lCZFIycGsKLS0tIHBqMkdOdDY1SXI4N1psSk1aOEV2
            RVVuTWoyT2VUekhGUHB2ZWM5Y0hnZVUKwcrj10byrOWa+6ES/Kuh72x1BxbRX5nn
            btiVx/9r1HGFgpwGw1NcWDSLpvJwh/YkHRZH3vfsvfbJAoYhS5uc8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g0exjqgq9l52m8g7hqkqelc3kcam4wwlkngzjhn5wv6dzxfjdceqdyfl4t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T21:33:23Z"
    mac: ENC[AES256_GCM,data:8JrNCfEl8H87FhMR+iCLWKnJMw/sjHac5b7TcNFjF6e1exOOusRp7GTBUzdhfxYOfXhh1df43JMrq9rBEX67aOHGI05pWUogXmbxaWxew9wU5itnSMIxDqK144WKjWktMFUiDm3wi8/Hl2iS9p2nJ5kgISuoscuoC2JJGPKL4Fs=,iv:CbnGGjbDPgZud882MMXVo6GPCxwmsukv4m5Nzr8pLZo=,tag:5RTl99IHBsLjkwFxJ1LXFg==,type:str]
    version: 3.9.4
