apiVersion: v1
kind: Secret
metadata:
    name: litellm-secret
    namespace: ai
type: Opaque
stringData:
    master-key: ENC[AES256_GCM,data:EuKBReTz/CsCHag1PkLMu0bLurdh8KrdsnyCXn+ktal+4CoEUKDA2mYti4WgLmPkmvYXV3ysUNMn,iv:3KGKCMrZ+tDnfe1qsmuyF5WszxTl7g2/+G8qR5pYl0k=,tag:L2wacplAHjFiQtVi0UViuQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTzIyaWJ2a1M0QlA5OVZ2
            VS9oMFRIdFJqckswcm5wVERJWTg0TjV0NDNnCm8zV0xONVlTRDVQejJSeXhkVWFj
            TDdIVW02OTBVRTRJRHF3dlhaeTB3ZXcKLS0tIGNRc2dlL0hjbHZRVFE1SnRPWG5j
            T0pvS3Q3T1pQSU5RSGg1SSt3akVVL0UKmvXnAfGNTOomw/HfwsMB4CY7tV0P/jRQ
            AhwyqcOR/UL6+J0ZSO7wHfc7qd+PN3kntcFjYLXR4aD8Z4qrGeOg/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g0exjqgq9l52m8g7hqkqelc3kcam4wwlkngzjhn5wv6dzxfjdceqdyfl4t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T21:33:22Z"
    mac: ENC[AES256_GCM,data:IYEt0rEiEgJwNMiWJXT5FTRhtUJ8Y//JSO+AkPT/Rszn1WjOm6X/lUX9dnZ00cKRJ6IV6U44xju/ZBP/hEpLa/lRYPIhTKbrfT2ktADSeP40w/kVgdErsM6e+eHStZLtmySW1iSDFfA0/kOVxhMK3uSOaaQnxHSSFJjYyKDNbs8=,iv:9fNB1+uGiF9HoSEHmeujfScn5gT1AOFtgxAFIt7g5JQ=,tag:acGlFZFjVFeb4zrBHkGTsQ==,type:str]
    version: 3.13.1
