apiVersion: v1
kind: Secret
metadata:
    name: litellm-cloud-keys
    namespace: ai
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:GQNxuGvJ74sfbhEgyEGQrxPnp3q6zmWY9LV2Bql3HDXiCUOkEWP0un6wIuEmPJmvmJtNnweFbVOgOIlpZHNHBGHt8CX+uUBnqqElBz7HgI0LFmtnrk0ckV0aDpdKJErDpDMmvHb1QCJ4iZlir9cKSnFayRiyL9IEu/+99uR2dgSB/2wGGVm33LY7tFg531oOgzQzGjv8IKc+SWQLIhaxn8M3uj8=,iv:shKV9crrGNRSNTHBehAgvpbvXNBV+IQAZqCwuf9EBRs=,tag:L9F3U/DTEEio4bfNnukojQ==,type:str]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:1Ahk2ZBsZwt0c6nlkefZJmuNpk4JKEL/wNRkOGIzf0ShR4u2m4q6mNLkQQa2+erXa9MP1iYmVRphWeOhfrkIzNuzaDp1baDTjrijSL5OMNvLJxkNgjInNwlgnSPEZ7VnQdLpjyyJThn7tqLr,iv:0E/K48FAu7wTT9SIaxZ2casvY2UzQ+fu1Zz8qxRqFy0=,tag:ywjooLkMqRMFmSBFhFUwAg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVGdSNyszZ012RktJQ0hJ
            b0lvTEE4K29hem1EYmxFYUlmb0NFbmdxeXpFCkFuc25KVGhMcXhjTXE5Si9JYzFH
            NVAzaHhlRWhkdjJzMVdGWDlQamErUEUKLS0tIDF0LzYzbEgrZkNkbUc4WDZnaXFV
            QXZSc3JkTDltRW54VTFuWERDcXhIL28KR6xsXOlar9SICfC8NoV2NYtQ+0tyqeXP
            csaGZNeMdsu1Ep75Z8SwHYY7kXkWlaWeedbmSK7TTZHPswt/K7OXIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g0exjqgq9l52m8g7hqkqelc3kcam4wwlkngzjhn5wv6dzxfjdceqdyfl4t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T21:33:22Z"
    mac: ENC[AES256_GCM,data:x9kUJ+WwRzIcRPVX6MSCDB7+WLZ/9JAS6P4WdBqTkblVpm1SNB3lI05zlqIM3wmVZ/pBkvY2ivtBlPK3jrf1G7O0yNrtqQDdxglihlrsDWszky3lUTNOEZhc13u9Cdeliq5YDhWgsR9XFbAFR8Z6nE/KxzmBzcDrFErtBFGX3NE=,iv:zWiPU2qdJjBuS4J+x+EDGqBOz5LcW+x09yaishJVwQE=,tag:3XOyooe9gbZuwrKsKtDPOg==,type:str]
    version: 3.9.4
