# Open WebUI OIDC client secret for the Authelia client 'open-webui' (env OAUTH_CLIENT_SECRET).
apiVersion: v1
kind: Secret
metadata:
    name: open-webui-oauth
    namespace: ai
type: Opaque
stringData:
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:RyKVzzowJobXeB6YT5JqQIjrw1i6DM4KgABL4OgrMWg=,iv:Mu+69/DOBlU1gxjYGmBsPRezaL6MWAaQTM27Li9SLzQ=,tag:MrLcSt22IaIwi7e2KjpU4A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSODJUNDNyNXNFZGY3aERi
            Q1JhZ0VSVVJjSFZwWXF2SUZJby9mbTNGN1Z3CjdDTE05Ykw4dnk5TzdUeVc1WE5r
            SnAyaGZiaU9IRVFkY2cxUVhHSkxCeDgKLS0tIDQ0S2RCbnhremJ4U3BpRVRBOFVy
            WUZvZjJQVmMveGlYSXZiaDNQWURxSlkKZXxAbPUr+sy3sQD6L7mzR8fZUVs9SDu6
            adyo4CTVAv+FkgXv4pYFQ65LVCM6fijzKG7kmiUVM7Keh/+g3oZ9Kw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfa6hhdz9egnje3nwa2k0gpk5nr29nyvu74eprk20m7ql4fhw4esrlmt5g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWnFWZkdUdDJuZXBDMlNm
            UlFHZnRNcW1JRUVpNTlmbEpyRmlhV24wZ3dBCnJOaGRieXVCL3VxUVJKZFdMK25S
            bXNEMGVnOS92Y056eVNMMExYTTdWOGcKLS0tIDlXcmVvQXhoaHlsQ0srai9ocTBw
            aFZqbmJNL3ljZW1HVk5SQ3ZuajdmVVEKFyc1DVDa3tUoDYs+rKQO6N7iSm8dCFM4
            sZLtU0d8qQ3xEIRYgKs4Zyvs2GsVNWHi1buG4Pg8gQ8iyAQSM8NgEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g0exjqgq9l52m8g7hqkqelc3kcam4wwlkngzjhn5wv6dzxfjdceqdyfl4t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T18:48:00Z"
    mac: ENC[AES256_GCM,data:YM+qSCUwVC7IYk/2rxsmsp/VSAaYGTXLYQVW1vTRX6oxCO2U+AhKdV4Jrsls2dpcBJOoJ1XvxTdvgi6Kw+Z8wr9mENaGFRLn3r5g/0IM4RoGM4fRhA1hog4R6DDLnbeZoKrzfgzGiR7kSUKpNlyH9OA3p5hcB1Fj2uRrhnPITzg=,iv:EZvELvN3eSYM5EA4s/TsotQ3Zrd1vBe4V05nrM5a/UY=,tag:s2YDDnvah9hV5fW88ngL6Q==,type:str]
    version: 3.13.1
