apiVersion: v1
kind: Secret
metadata:
    name: open-webui-db
    namespace: ai
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:51ae1irlqgOy+b4x4Epi1nDDt5GJl4pl2jfyreYFTzUaFyol84fsv5FYI5XTIb23HdifTnkmjBSTtSz+Ouyzj24q9VzIG2UN5kzaBOz/Cxrr39ivy2BhLFcAM/WX7nyMGMSWm55U04Cc8m3fn658elYI+CJPpA==,iv:FqbwkqRDYuwJ1wRcubjooQI9bXHSXXP6hXZELr4dNW4=,tag:QRaKXk8BPumV69h0cRpWOQ==,type:str]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:z844cXweR0NugXowM4+fVCXiBXtg/TVlTJsYBFdpFGMwtDF/2KwD0QXzEO/LSVMxT6ouHHDP8gA722kAxfJruw==,iv:PxaU0keCNCsnxsvMi2d6pDcxfQK9OY2JWxqQw2riCE0=,tag:l8E5DFfQy9QKFOGbi2lAaQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQys1SzdOS3JjYkxFdllK
            M1RDbTh3Z1REOTJQWjk4MWpVejZFTnc4WHpnCjVrMHI3S05tUHBsemFWOHVROVZS
            M2NWZlV4WW55d3pwV2hBM3A2U0hmUFUKLS0tIGs3U29xdmh2eEJWTGNEakwwaElM
            Y3c3ajV3WEJNeXRUWGkxUk9mK0J3MUEK5Z5MCNwRg2vWwyaFfbr6Y3sGp80oTaF5
            mFQ01azgTA4H6DUnpAZhfLPUeQG5NE81r5i4naUh7pSVnXoiQqPtJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g0exjqgq9l52m8g7hqkqelc3kcam4wwlkngzjhn5wv6dzxfjdceqdyfl4t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T21:33:22Z"
    mac: ENC[AES256_GCM,data:pZoOux9yKXHv6TBWMdPaFMfzAhecAmVUU1RvuEdcVN462tY0NjbzWfDrhd6ngXxxheCqGjrlC+87hwVkGvBlaTWLypO059UsxkACk+X9THfH4BA6vs/tyk9SSe/wZFJVOS/qCAhFNoG31wOxmjDLgknYhX+1JNN+UscCQwr+uwo=,iv:uABcywxwd/cjLwZBLmlxiuVYlQv7cvjkrSa3ro2F0mw=,tag:vSivLL25S2lu+sDG9LGK+A==,type:str]
    version: 3.9.4
