apiVersion: v1
kind: Secret
metadata:
    name: renovate-credentials
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:pOeRlaZdK0ph4E+wGzg/AW0l2lbdGN4r9jdS9viYM5uK4bbm1IhQktWuQkIHzjZridjpkTYZLB8KV4Wr3MlSIH6NubEuALJnpzRVknfqQ4gJL4cd70d4FFkrPCkl,iv:GWSbkEQe2i3WCn7hQ1BfOTbQW436fl2lWb5eBikUi/Y=,tag:DSf8UqqBc8+mBqt4F871iA==,type:str]
    RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:W4kZF+3ZCHoeWjZjugyZjNFW94IIn4PykyUhsLFanRrRbUEwf7Y6HMOqyNSSVzR1YQNLEzUHj+4e/fWfRHSREZ/X+spGFGuiPKe0vy6liJnPxW7sB2ApSBkkoUmo,iv:V4+8ltNYcLScw7jUYYxIX1wlnhgjNml19CM9h64Wk3Y=,tag:4RLUfPudzyByiRkWmOc4Gw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMVFZRHFJWSs1T1BBaW1k
            N0VZenVhZTY4Zk83a2hxTjlPUnM2ckpjcHlZClR6ODlBOG1JVVkvditJcDI0cHE2
            V3ppTjQxaW9YbWVlWWFGRk94UzRvdVUKLS0tIFY2WFRjQ052MzFaRW4zZnJFdHVW
            cGNaTjQ2Y1V4OURMREpkQTBLUXRQcVUKanHGl9os3j8EY15I0hGe2Kt4PCZu6oTG
            5un180Df84mDwO16Uq2h4ijmHuLgvKenSBlhOXj8GvekRwMOj8fCMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfa6hhdz9egnje3nwa2k0gpk5nr29nyvu74eprk20m7ql4fhw4esrlmt5g
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T20:20:03Z"
    mac: ENC[AES256_GCM,data:kRf3nwXyBziG9xSBFA5CKvCBm44jRVB+I62v0JdqhO5r63RZM0vpJgAacA4aPQQQPrWQ7nePxokCfBZelLaciuODYKDc9RLxgIeW4Fz4G8MdrSYr2jQQQsoUSICZkEoM5Yi9rIEZhw0q/ycd3lb+Q6t6OK2ENPAPaejFJFPXiWc=,iv:tUadX+AMI4rN/l0NiL3CQjQvOsTOUuFoKcX0Fpzor3k=,tag:3dMaq5gh3J5TmvXOYX+d3Q==,type:str]
    version: 3.13.1
