apiVersion: v1
kind: Secret
metadata:
    name: renovate-credentials
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:DHtGlXnwWzQJbuYQrVvHJtoh5Z1Fq0f9bdNSErS+RdsvbOKqN/Z67w==,iv:2f4p35SyInhQ/rO0NA4CzRHGMOe5Bm7r3OlosXEWf6c=,tag:Dnfbv92eXoXgoFW13ZAiYw==,type:str]
    RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:y75JuQUfkRpMDgwxErcLPOFpC36qfqAICOq9YF7YY0VFeF/SqlMyTOVNvUz2n4hOs3UkI34YVIGjZrUQbX5DJW7eSWZWfvBBVt5VzYDz05flOZOM5amcX6oFPxjJ,iv:V4+8ltNYcLScw7jUYYxIX1wlnhgjNml19CM9h64Wk3Y=,tag:XzrXoVOip16RXDvrh0HIdQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNUhIeDA5ZHRKazlLSWZX
            Qm1XMUNURCtBaGxzWmF6cU03UnE4a0xsa2drCkJFOXZzb0VzUStpRm55YmVEcHVX
            ZlVDV1pXT2RJOFduWXhJS1ErdHkwdmcKLS0tIEhabUJQdUFRSWRBTmh6cWhxaHFr
            S3JucTB0Y0R0MTZDVm5SYUd2VUc1SDAKFslDISRwyuf08sH8re3SPp714gUupRCw
            e7I+vixCaYp6Ew+MUlRnAHbU06+rg4mJGlxmXVu86xyGu99+9B9bTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g0exjqgq9l52m8g7hqkqelc3kcam4wwlkngzjhn5wv6dzxfjdceqdyfl4t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T21:33:23Z"
    mac: ENC[AES256_GCM,data:WzHLM+rqaiFU7xHuVowsr0cNX3/FVEYLvThn2A2OlORimC9yEOiNenCoyLrFJ8hw78QiEoyHo46vppZBpr5/w35JYjAQEtdqfYhKNkI4bSk11yJ+LraliRZ2IvsHXOiL0I4WOQ9hHcG2O0ePqSEL1ErDvUkrt0r2XY6L02KsK+M=,iv:h1ypURWgWometIWg1nF6gpFFYu9VLj4XP00CZ8/kFP8=,tag:ReB1Hk/0tI5KCk1SnTxUiA==,type:str]
    version: 3.13.1
