apiVersion: v1
kind: Secret
metadata:
    name: gitea-oauth
    namespace: gitea
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:UhXugTU=,iv:U9P7o6oQ31jst8orPQttYlp49zsklb5TaLg7pSXREGw=,tag:DEK3BARHQDVzpGRNOn4GtA==,type:str]
    secret: ENC[AES256_GCM,data:dP6lpf0HDw+cXHAD2NowQjlOJKs1jYB7RkTCcVyyE4Wb5ZcHknm74lr1Gsxgs0TcPr2RWntWQejyMyYchGQV8btIQdW6yrSc,iv:oEw43HW9yVuj0btKxwwEay/ed2PsCYmxXPEG8BpeW84=,tag:OL93zrjdRkORBfRcbzGxzg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eEpPUEt3c2pvalhiajJR
            S2ZRbFhwM2JSdVdacDBRQTJpSEFJbEhRVFJBCkgzZXkxeVhMTmVKK0I1czAwS1ov
            ZUVFQ0tZOXVLRE5BdlJzblNMdTdxUzQKLS0tIGNsOG9VSEdTM25LYzMvNWVkL1U5
            amtmdkRhSUd6WVZSWUdRa21RNmVmSm8Kwr3hZP2fVZ/bsR4CKPjzB5VbVrlS6LNz
            NaUa+EbpAoQVdkOp5QFQeoPUHiGmDZcAJnJnTwPsITv2AgFtAmEZRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g0exjqgq9l52m8g7hqkqelc3kcam4wwlkngzjhn5wv6dzxfjdceqdyfl4t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T21:33:23Z"
    mac: ENC[AES256_GCM,data:CpuRwd+oA7DTUl5EHZUvQcPNLOXKLGrh66Ux6PRuT//sAfaTcrg649qCDJBJ8wdf5oCAkmVsl+oEWSfKBjpGMg6Q0ufOCdJ3Sqded/0QQkEGta9eCbzFux7uHIby+hWYK/LGJfpAza1sFld/H2Oz4Uto4jOQSE7Zm/KPuy6FY/M=,iv:kJUyl74GnWq+X6xhSpJFUcoSrdR5sxgv/32NnD7Rp9U=,tag:jsTl6j300Hu+h8qkVfMpCQ==,type:str]
    version: 3.13.1
