apiVersion: v1
kind: Secret
metadata:
    name: gitea-actions-s3
    namespace: gitea
type: Opaque
stringData:
    access-key: ENC[AES256_GCM,data:jvJFjs0WlGxvFEa3Jou1HG7H/Pk=,iv:tWwJABNcDms4I9rqf0GoQv2PURogKNbJU6E6U38DI1Q=,tag:uHUFbBwIWCAI0Cre2s869A==,type:str]
    secret-key: ENC[AES256_GCM,data:yLJeqqvx3wYEL34UvEjI+P/qAyWNoiKXu21HImfyDd8dXf9Usk0ejg==,iv:ZQRrAHuTGdkcXyG5NbAoYkIsEic7N3/sH0Y3IagjjNU=,tag:kBJknjbSXhnpleLw9JShOg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNGtjbm1yUjZFQW40d2tV
            RDdiT1hqbWhCNDh6d1l4YXV0a3l0SFpUSEdBCjQrazhudnoveUR6bURYZWhoMFZX
            cEl1STdzZHAzbkc2aER0RDZwVTk1YW8KLS0tIGVnSEdoWFhaL09yMXA0em9sNjZ0
            T3duam9hQUNVOElwVm5OTzBQN3N6RU0KXkW1n6LOLCxD6k22NwWKy4NrUEs9Rloh
            t4PAKmWJf4G8EMpcP8tAwd4KV8fE8sCeG9IpTem4Fuf2eQKllKIa+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g0exjqgq9l52m8g7hqkqelc3kcam4wwlkngzjhn5wv6dzxfjdceqdyfl4t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T21:33:22Z"
    mac: ENC[AES256_GCM,data:cywMfJ4jG9bPm4dhAAZtc41zpjCMUmX6/fWKlnBC261gN2M7LZdMGITEt+GbObS0wn6KtW9NSz0MWZInXIUZebdjmCAKrm+yd4RDxjTHXCmXoXg1VFo91aP3dR2ug6KkL7Wqxvd93xSzwMTKNNblBfhwqJc7c4+632SOTD2vaRs=,iv:kSHs0JEFncUKMBGUT12DvVqMoXyK4qRCivCK4LWAxGE=,tag:4SJVfBFWDdE/ngVpTxr9ZQ==,type:str]
    version: 3.9.4
