# Gitea's Postgres DB password (must MATCH infra-pg-gitea in the databases ns). Consumed by the Gitea
# pod (GITEA__database__PASSWD) and the one-shot pgloader migration Job.
apiVersion: v1
kind: Secret
metadata:
    name: gitea-db
    namespace: gitea
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:VB8hGfA=,iv:tBEZ6kiguAbenrfmwI5DA0M1/Zrm6czbF51vNEFQUaY=,tag:cxQ8CXCm2qMWsr81LNUjqg==,type:str]
    password: ENC[AES256_GCM,data:dEcy6nKYElZXvNFEpMTU/6eUf6xLmRkjEeVff//iFQ==,iv:yN5FpP+x6tWjHGcywSIPrbZjXDyFamF3VQ6hRmyJLvs=,tag:Vm1d677KGA+eZL2Q7W2T2g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpckd1aW5sYmVPRUlXYk90
            Y1poeW9vRW93Y01KZWExMEIxOHU1dUVZVWlnCmF1S1dXYkxJRElXMzJYWFh4dnJN
            YnFtZGtiYjBpWlBMZm1XYml0aDRQTXMKLS0tIGF5Ullrb3EwK1JLb1p5STVyN1p6
            REFsd0JlTVhTMVNLcmYvVTV2M2p1Q2MKAEr5BmCTr43dqaTajvzTppyDqavO3QKs
            CaEUjc/9gOuT8LPpil0IdiwM17EAwZ4qY0eNTlEkAtTPIPiroRzN/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g0exjqgq9l52m8g7hqkqelc3kcam4wwlkngzjhn5wv6dzxfjdceqdyfl4t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T21:33:22Z"
    mac: ENC[AES256_GCM,data:HV7Auy9FnULFD6aJehqVrCihkO4fjd1nc+RzFRFaTT1T5rEpAp+u967k3bsK8F4WEvVf0hNX7ydU/x+Y30TA/OZDlgGvWd2LnhVPQJREeIhQxsaOTeQdw85SOH0uZNg2NBmW7iTzZeck8AO51ILORbHYTPnAhVVvrFZhfHYmq+M=,iv:m5dw1SXoGMRq87gH/lLF9QzwOzAmOVbSQ2sUs+QEp7I=,tag:G+9G5T7TEvEqdbix9OsW5w==,type:str]
    version: 3.9.4
