# Grafana's infra-pg password for the consumer side (GF_DATABASE_PASSWORD via envValueFrom).
# Same value as databases/infra-pg-grafana.sops.yaml — SOPS cross-ns duplication, repo pattern.
apiVersion: v1
kind: Secret
metadata:
    name: grafana-db
    namespace: monitoring
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:W6vgIVruYL+xSEUxAH3OXPaUhsW5+PTY4eyKXwpQfqtTjOG38uzZlpcBXvi0prwd,iv:OJVEdFYE9zWWmcXFL6zJmLFgEe6RBAF3dTBQv1MWXBQ=,tag:hdfJ8QDgrvL6cRaifOvQmA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnckhIRzBkMndmcDUvZHA0
            Nko5MHlIenNKSHZHaTg5QUxEUGFYQ25PMTNBCjdPNi9nbHpLZE9BRzAzZTFLOTNI
            Z1ZncmgxVGo5d0J4SFpYb2VkczZ6U1UKLS0tIGgrdFZ1ZFUzT29nM3J0NUQ1TS81
            M1VyalZrL2F2QmhoWmRZclJEYVJjYncKqeo59JHcnmj9IEKoIwFCly8zwPwI34h/
            xqN7po1/bM2hlr8Sg6Uxxfnv2RB8KN+B3HccA/0s95hjAnnEgxjX6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g0exjqgq9l52m8g7hqkqelc3kcam4wwlkngzjhn5wv6dzxfjdceqdyfl4t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T21:33:23Z"
    mac: ENC[AES256_GCM,data:gGPRVTefPL737MHgDpTCoeUgoX2LFVrCtI488Rf1YmVnOP/DHiVaJ3bO1mrMAmJhRecjJt3O2ngTmtkvFK3/M9UEKSQeQDevXPJucOONKI606MrNtBT8XcPkYVwPOW3vkWyj/qCS2uiTneiErfGik/3Y8i9Jrkcc9eZjAIdhcvQ=,iv:gkAzVGSlEGU55uI3J89LtOjA4K+6T1lcEPCtcfJGI0U=,tag:cYTs8xUXZDt0UD4cV1a/4w==,type:str]
    version: 3.9.4
