# Grafana generic_oauth client secret for the Authelia OIDC client 'grafana'. Injected as the
# GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET env (grafana.envFromSecret), overriding grafana.ini.
apiVersion: v1
kind: Secret
metadata:
    name: grafana-oauth
    namespace: monitoring
type: Opaque
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:jh9dCCO9xvHbowmXHVpBrEv5pJ3srAlpzzulDeivyBo=,iv:4/repSwV4pHwhlK+zYno66HWFoP28JL9Z9Mp7OmDWNc=,tag:8yyA4HdiypRVkcPSE9gC0w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZWc3OFRoN3ZCdnN5STIx
            SVJtYzF1SHAwVEVrOHhuOGlGb3RJamo2b1dBCjlEV21YK3piZVBja2xNTmVVSmtS
            R2Ruakx0VFhqMXJHTVFST05McEVmRHcKLS0tIDhDNVZobXFRd29IVEFxQmxUaXVL
            cHVjV0pMLzFwMkJMTjMxRE5LWGo1cEEKyllSJEfKOTcN4QotTCVHnyPq0EUrWOX7
            yl24HX9W0jyGXci4ki7fAOhK/YqQ6LK5ejOWWWUduZou3j+hUMvV8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g0exjqgq9l52m8g7hqkqelc3kcam4wwlkngzjhn5wv6dzxfjdceqdyfl4t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T21:33:23Z"
    mac: ENC[AES256_GCM,data:eem1XB1T+lRcCSCz7cvApn7wf54bZGoy4Et0lO+S0z5f9FSYFLyzKxb4njWequTpR3FUmjCf6L9AvsP8gp/XP8sq+Co4q2R+FnHt4GvP0SaoTtTcaEiAkW8inGaryKk6bwcLM6bjbESeNR64xNiQVSKUoWdMFUorV6ecEl2v57g=,iv:EDPipLBCf+vl4F2OFqRifi9azYZh5twng6FCwzMGEnA=,tag:lBT1EB9+LBve3GjcNOLFbw==,type:str]
    version: 3.13.1
