apiVersion: v1
kind: Secret
metadata:
    name: ntfy-qnap-auth
    namespace: monitoring
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:t8HvHI0gEIQywultcRUGKQkAxRnP29Dy,iv:Orox3Ad5soFSEHJGacL28TeKExJlN6aXH93jY0yFGbA=,tag:/CRGVP+jxkEqCLtFeb78GQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpYm9uRDFJZzZsMENoSzA5
            bXA0MllXZGVIK2lxZDkvN0Y5T0QzRFRTeXljClpiQWl5dFBBVlVkSlBBNkRkQVpF
            ZlhPSkNqckF3YWNKWklBVHdtR1RSYWMKLS0tIHRFc3NabzZtMlZmQjA2emduWGU5
            eVYwYm5vMCtxczQ1b1l2dHdsUmF1ZlEKH14tEnWHxCXo8pc7E/5Nepm/l4KaErR9
            2qEq6PaOZuCan+LZw6i4s3LVce1dWhhiVh2f71Uy+ILQXtYe7Md3dw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g0exjqgq9l52m8g7hqkqelc3kcam4wwlkngzjhn5wv6dzxfjdceqdyfl4t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T21:33:23Z"
    mac: ENC[AES256_GCM,data:7DFVfOmUq4l8FFfGb9WhZsXr8PoeXiSgKN3r7Pxuy0W7mOqycVbLZBbXuxCdP1psRCcxq13YgWAZaeP2E+qyeEK60iPZObkAbkpw4s0+e3epnPqcnoAERkWfmHhWY6p+t4v5f6NPn2ST0YZ/Ft5jyNaZ1SNiEf0BhbqCsz4K09Q=,iv:07gTYaP61pegeIQVunoK0fkuqw0lfErsoZQcslzytjM=,tag:JeMMNuNHeSSVeb9Kks15Fw==,type:str]
    version: 3.9.4
