apiVersion: v1
kind: Secret
metadata:
    name: ntfy-auth
    namespace: monitoring
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:Rc4ObcmCqoa2cXpLMFPVTqpU3ieMOPuOZb3xpw==,iv:T4jZggV6u9UiegCSKf3jjlEMqJPJ+eT/9jWq+6/qfuc=,tag:3lITsnzeKcpVHlpXtYE/vw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VVE5azYvZStVRmdVL052
            QUw0Q08yMlRqNTZXNktQRi9pTU96dTJJVG5VCmJDellMMm94NFVqcEdSRWJPRUdW
            Vm9vQ1g1Ym5pM3hmdXhhSTRhc3NPRlEKLS0tIENrbWsxNmtFOC9qVFlSeU9hVVY1
            UG1ldFdobVFXQmpjcW9KV3ErVDAxN2MK8qjnhNl6w4NuUViUOzkdh17srMW1FK5M
            pFjcHd8e2kplHxD0NZW0UtXOpZXwBCoagD4fHYaZDzV91Rgj0CBotQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g0exjqgq9l52m8g7hqkqelc3kcam4wwlkngzjhn5wv6dzxfjdceqdyfl4t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T21:33:23Z"
    mac: ENC[AES256_GCM,data:zgxma6RNKtklLcBtvIJVo2QABGVMdv2DYvq6gg9t72HADohhBxWjETkD+X2CbCOOF/aZbJkR7rJ2TdiAEYKmbZIel5IXPDVFvw/cp3pkhEN4ihJSNsZOzJVmX5BF+BI3IFfEOzUWN1yZExTpBHMkKCX5UQgC1MB6HJK16LTd8KY=,iv:c1ewVQZ1JkGGFrwrdJ70aqznScdLhY0CTPbgU2wl9JE=,tag:FNugqjraHUQ4ZgEBGHijNQ==,type:str]
    version: 3.13.1
