apiVersion: v1
kind: Secret
metadata:
    name: pve-exporter-auth
    namespace: monitoring
type: Opaque
stringData:
    PVE_USER: ENC[AES256_GCM,data:b0idPJh7U9H3YrFkfII=,iv:GPf7eeHqfIue53E3E/zXI9xVsdroo49Vx8y8GtOhgZA=,tag:6wuwBr/+xBdJzxRX60mNsA==,type:str]
    PVE_TOKEN_NAME: ENC[AES256_GCM,data:YDVcV5tr550=,iv:4uB6wgrbMyTFkmki1nqRkbzNXVdnUmhBJddysWkRKJQ=,tag:F0LyCFR4gWwI/Dch+MzdTg==,type:str]
    PVE_TOKEN_VALUE: ENC[AES256_GCM,data:Tjt28K6kZgEm/BTNvGX4vX+AFUfPN83D7JzkBORd4nliflUO,iv:SW5MoDzhcyYl1/STAdHinA6Q4nAHeHfmcQT2tvBOCB0=,tag:UWf1AjTFj1uXMPJotwdaGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMzdLVHk0TGhpTC82SGdr
            Y0RibUk3UXBrQnVPTWM2ZXR5MHpsOWJ5YVM0Clc4S1RPTW9McytjRG9aSjFmTURn
            MmNvUTd2MUhMZGkvVTljMzNNT2I2UzQKLS0tIDBzcmNSVGROUXc1Vy9aa2VIUDUr
            SngyTlN5VVVka2ZEQmlIaVR4TExlWWsKsGf7Ysnqtq+FddigjPeCVl8HcDIdqTcq
            fYuUMVtvFH+fKx5DixiLvQtzA4wRK/Hud4Ho4LRJhHe78pzQQLJxlg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g0exjqgq9l52m8g7hqkqelc3kcam4wwlkngzjhn5wv6dzxfjdceqdyfl4t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T21:33:23Z"
    mac: ENC[AES256_GCM,data:uSkngcCpyjyjR755n/h1TSKIUsHnZ4OEki9ACw3MmTjZwO37/CX4aB3XyBn/CmNsyo5sto+kk6Tqc/gAFBf04Yy58uLuZxT24iHsvok51CKdjfnl8HGOCc+q/L0mBXvZeGl4m9cxTAAerUf71nXugbAIescZSA+GcHEFYmGVXTc=,iv:XXeAymJiiXuEylVwh/BGQ0F8mrR4Kp5Edf4pHamQrWg=,tag:QNaw1wgAS0feJmAv/vpM0Q==,type:str]
    version: 3.13.1
