apiVersion: v1
kind: Secret
metadata:
    name: pve-exporter-auth
    namespace: monitoring
type: Opaque
stringData:
    PVE_USER: ENC[AES256_GCM,data:Zscyyb0c8XzVT4RM7VM=,iv:GPf7eeHqfIue53E3E/zXI9xVsdroo49Vx8y8GtOhgZA=,tag:lsmk5bhRN3h28ZC7o8958A==,type:str]
    PVE_TOKEN_NAME: ENC[AES256_GCM,data:Zi48VChLJCU=,iv:4uB6wgrbMyTFkmki1nqRkbzNXVdnUmhBJddysWkRKJQ=,tag:EqPcvZ1eUCcNAL5JHvWXjg==,type:str]
    PVE_TOKEN_VALUE: ENC[AES256_GCM,data:bRNM9tc4Bygm4pTDsfXva3iz3Rg3ZI5Gf+JQOmS+DLlDNCz6,iv:SW5MoDzhcyYl1/STAdHinA6Q4nAHeHfmcQT2tvBOCB0=,tag:pqXIk7rWGw1U7Km1/ODZ1Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOFF1S2NRVXlqT05VODB4
            UzdnbzZKdE1aV29CT3BjWnMrb0RIRWszZGlZCjd2MGdPMkliTVQ1ZjI4N1lNQlFJ
            eDlya2NaQ1pyMnFraVpLUWdoVlNpZ3cKLS0tIFQ5VTVEK2x6cTg2WWRaYnM2Nk1N
            c24xQjZlam9KS2cwTm1SVU1uTm5zWG8KITXU6cr3D8BdT/kDL8T7N7DbhtbEYV94
            UN+AvRx6VfjrFQyykw01JeefSAGOnlQaoDNNIo+u/Q8YeretiRIOvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfa6hhdz9egnje3nwa2k0gpk5nr29nyvu74eprk20m7ql4fhw4esrlmt5g
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-16T11:24:53Z"
    mac: ENC[AES256_GCM,data:KxYzSBrB5r4WryWVmI4x98XOqYTW5J1kp7wVSzYOU6jif4wLwwm0HXpyFkVO3IcF6lRGzplXVbU9T6ToBYWUxO3g4UNivaetuaIXlxC3EaY8QMgDz+WqaEtKsMWaZZQKuewJpPCKWaRYVa+Mm690YkbJ0xhA5Ot5o8Wb2C+h8kU=,iv:Vr4t7GULDgRjOaAFMlikfQWb2zaKhWVVasY2KzI447I=,tag:wlZfNYt6435+Ks7r+/UHkA==,type:str]
    version: 3.13.1
