apiVersion: v1
kind: Secret
metadata:
    name: qnap-snmp-auth
    namespace: monitoring
type: Opaque
stringData:
    auths.yml: ENC[AES256_GCM,data:tUkgjmslO4QtMW/VV/P2FOrwpvnGwWSCvHPj0WPIuLt4S6fjCiOWwNzMZQc9B9gOPsyoqFWe+s+BqVejFRQ00/xBzsR2PFzVT06TNKPHc4XFJw==,iv:lOMaUoL7G3EwnU4nPO62enRGFxQNbSHdh5tcMfwazSE=,tag:99vO1yqpafvwfUZeSkhXUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nfa6hhdz9egnje3nwa2k0gpk5nr29nyvu74eprk20m7ql4fhw4esrlmt5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5K2tvVFFxenlOU0UvajNm
            ak5wWm1XVkJoNWVLd0RldnVMR2VMZHpYU25NCm56bkZTQnAwUkZ4TksrWWxMeWRq
            VlRaQWJMT3hsYVF2V2VwY0p0ZmdVMDAKLS0tIERUckFqYi95TlFPQWJRcEZhTG9L
            VXNveGFjOEtYZk5tbU5ZcHRrc003TXMKAPh/mB4ofW4hjV1LezdhU98LV/ZNcDqW
            JJh519PnvBDpKbHEpQu1lqaSGJXYwRuSEQNGHIJFHOZjkSI+HqJpFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-16T16:54:53Z"
    mac: ENC[AES256_GCM,data:Wd7uJIrSu3ROhF9zHjQC4oo4UxlRxuPaCpYQNj6mRv01MMumVjabHwbo1DTSDc2lh6cuc2/e+9o/a1re1Sj7Jq31Updwe02kz/AUl5GNP9IebQGx95MTIWDZJXK6PElapCp+Bd3XyVZYhztT7pogmcJRf5iHK4nn58b9E9DACys=,iv:xP76ZRkUrOUJofZOlPL/BCCgaL0LJuQ8HliluDulPhA=,tag:CvBBqVjmsSegBXxD5Ov4rQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
