# Vaultwarden /admin ADMIN_TOKEN — Argon2id PHC hash of the admin password (the clear password is in
# the gitignored _out/vaultwarden-admin.txt). Pasted verbatim; k8s env is literal (no $$ doubling).
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-admin
    namespace: vaultwarden
type: Opaque
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:Sh9DgMJDVeFevLlkYDwvcI4GnSOSXoPVXW4rCn8xCD5M8Ao8r4JbdQwyhc9QNbhDRmj2stud/whlnYyAtIr7Uv5Rs8RMnMb3ncBerXZ0cR/bZND1Q68kx0RQD2GJjOr9Ww==,iv:X04FHFYD5r4mLFXOlvcsiI8QZD4L/tOd/qIEtEhrkdA=,tag:owt/PZjXpNw6A4KQll2BvA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQ2tEcGJuTTBiL2ErZlRn
            N2FDVllmUVZ5MGN3MVR2R2pnVWtzaUl2ZEV3Ci9zanM3bk5rYlFzOVlhN0xtZjRx
            TE5LNkNKWlVRU2hacnd6eE9DeXJCelUKLS0tIFNaR1NObWlXQmxZV2kxU2Q1RWtJ
            VVJZYUozNDgwWTM2L0tqNTZpc3Q2ZXMKV8uh2mp4y8dDykkkq2LgFYwDilxKUq9t
            iK30C6MotcXgTj3GvZZTCQKS/E6KBbeiNLXF+yxjfG+F6mChRb3X0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g0exjqgq9l52m8g7hqkqelc3kcam4wwlkngzjhn5wv6dzxfjdceqdyfl4t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T21:33:23Z"
    mac: ENC[AES256_GCM,data:EGqX08YO3kAhAqSDzaHMpdlZhWBJEg/sfMAp5f5aY1A8VvU6+YyVCnlLuH2FtdgnR+kZqAVWlGbBwcIN4Ya5KmIe1gtb0PhnDvFha9ea6qSdl4kWDe3wspterYJY/z7yAgy6rlRKWKiCYn+C3LdgF40k5wbYNWU74Aczndww6k0=,iv:NMs7akaWlUxb5dT+5JPQ39XIS82ghLxdjJFSUoPOueQ=,tag:PZ2JVuajIrUNjv7cBXi/KA==,type:str]
    version: 3.13.1
