# Vaultwarden /admin ADMIN_TOKEN — Argon2id PHC hash of the admin password (the clear password is in
# the gitignored _out/vaultwarden-admin.txt). Pasted verbatim; k8s env is literal (no $$ doubling).
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-admin
    namespace: vaultwarden
type: Opaque
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:FTt7afIfJRDiCuoZU+OHnwWZPaEZWRpJcVMXT/zpzjU1pio9uk61Ckxdy5RhcRwmv8B2tmm8eWHe6ZWWm1NeIJxJy51EHUyJjiPucenDe1AQFmLnTCZI9FgUIk/iVLuK2g==,iv:X04FHFYD5r4mLFXOlvcsiI8QZD4L/tOd/qIEtEhrkdA=,tag:2Xk96Aim2qMAMqxkvVl5Ig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLT2EzVVdXS0dlVFV2ckkr
            SUlnRzdIdVhQRk81ZU5SazQyRDhhRUk1TzMwCjgxQ281cTBYUGZnZUllbEhiRWtt
            TVo5Lzc1dVZUWUZLY1ltM1QrMkRRMncKLS0tIHNoelMxNHA3ZjdKckQzejRNUWZG
            QTh5clRlQXdUekJGWlpaaVJMaVRwYXcKF1YawOeP3vzU3RupACOQam7TcUk/v38J
            HB5UCtL3hWsYvSKd7wg0AqwEWN1Ejs8kAwxuDr88H83If/Q0XZszgg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfa6hhdz9egnje3nwa2k0gpk5nr29nyvu74eprk20m7ql4fhw4esrlmt5g
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T16:41:12Z"
    mac: ENC[AES256_GCM,data:I2DXhwmu03HRKgRv38SIekwr52dlTp7+2rCvo4BB+WIIGWItTfxHhZZoV1fbymdd8sbiDcdHzdqbhifEPXU3ZXccEjDca7CgAOtj/l5dQd2t2eNeNJ5t+N1xlJeljOrqzUfozR8ATsHohUzR+mmA8wqIeIbDdqpOBSnartl9OyY=,iv:uX9Jpg3tMg3/hSMS3shOpX3WuiS0xk/CFv7Ax/vffmo=,tag:MFOgBw4UuOrrgEi1xuV7Yw==,type:str]
    version: 3.13.1
