# versitygw access key scoped to the `velero` bucket (owner). Key MUST be named `cloud`.
apiVersion: v1
kind: Secret
metadata:
    name: velero-garage-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:aHFbY3+fEzsFg5m6uW1X05Mhoiz4We8TRwJjnSWzCDS6DwYMDAXRBGbepoebVNEdsu8XKl7wQRZBnEj8QLG+F9bqn7/1Nqibq8v7J4ZsDFOabZb8DXfwZjXXu5mb1vm7oCcrWTgACyueprzzPQTVUg==,iv:zSNTaqHEyVUZgp2qhN8CSw9bfvbHx4+cpo0b6qNgFIE=,tag:pT6omu64zykbQq+8qJDM8A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZ1NobXhYajM1aW01UE85
            VGFsZWd6NEdTRjJkbFpGME95VUhFaDJ0TXhZCk9iVERRc2U3c0hZTDlJa0FYekE3
            TFBuZmYzV1QzVHUvVFlmMHU5YXJlaTgKLS0tIEFBQlgwaXBUbk1STmVtZ0hhYnpX
            N0g3dVoyeVNtMlUva0pWcVk0UHY2RHMKR5TQ2fHP8bEe378LsIVkIlzJHTq2HNGH
            1F2a2dUvEzcdPfRCv4khnNeP29+hwjRYKelkcZTc/tTj3Ki/kzDvZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfa6hhdz9egnje3nwa2k0gpk5nr29nyvu74eprk20m7ql4fhw4esrlmt5g
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T13:04:23Z"
    mac: ENC[AES256_GCM,data:UG+S5h75TeQYJ+9RV1fqmgsqwixoeDe1zPIAqttM28nnqVd8Flw21EijxdRHCYbCE6i+lb4SVL8RNn6UTaZOq8fJ+aKuEGBzsFbep57RUc5BYEubQMM0dMj2ELtWlobEEHNroO45t5KL7a4nsVBuQdSYpvOuzBoeQ/XWee1EzDo=,iv:Yjk9Oht8Z+8/gkG6UtzftyvPc22m+3HBks0PA2L5gwE=,tag:sxnwfPsLAKUxmnHQ9qb2Og==,type:str]
    version: 3.13.1
